// 토익 빈출 단어 — window.TOEIC
window.TOEIC = [
// 인사·채용 (Recruitment / HR)
{w:"recruit",ko:"모집하다, 채용하다"},{w:"applicant",ko:"지원자"},{w:"candidate",ko:"후보자"},{w:"resume",ko:"이력서"},
{w:"interview",ko:"면접"},{w:"interviewer",ko:"면접관"},{w:"qualification",ko:"자격, 자질"},{w:"qualified",ko:"자격이 있는"},
{w:"experience",ko:"경력, 경험"},{w:"reference",ko:"추천서, 신원 보증인"},{w:"applicant pool",ko:"지원자 집단"},{w:"hire",ko:"고용하다"},
{w:"employ",ko:"고용하다"},{w:"employer",ko:"고용주"},{w:"employee",ko:"직원"},{w:"employment",ko:"고용"},
{w:"personnel",ko:"인사, 직원"},{w:"workforce",ko:"노동력, 인력"},{w:"staff",ko:"직원"},{w:"position",ko:"직책, 자리"},
{w:"vacancy",ko:"공석"},{w:"opening",ko:"공석, 빈자리"},{w:"applicant tracking",ko:"지원자 관리"},{w:"recruiter",ko:"채용 담당자"},
{w:"orientation",ko:"오리엔테이션"},{w:"probation",ko:"수습 기간"},{w:"promotion",ko:"승진"},{w:"promote",ko:"승진시키다"},
{w:"transfer",ko:"전근, 이동"},{w:"resign",ko:"사임하다"},{w:"resignation",ko:"사직"},{w:"retire",ko:"은퇴하다"},
{w:"retirement",ko:"은퇴"},{w:"dismiss",ko:"해고하다"},{w:"layoff",ko:"정리해고"},{w:"terminate",ko:"해지하다, 종료하다"},
{w:"severance",ko:"퇴직금"},{w:"benefit",ko:"혜택, 복리후생"},{w:"compensation",ko:"보상, 보수"},{w:"wage",ko:"임금"},
{w:"salary",ko:"급여"},{w:"payroll",ko:"급여 대장"},{w:"raise",ko:"임금 인상"},{w:"bonus",ko:"상여금"},
{w:"incentive",ko:"장려금"},{w:"allowance",ko:"수당"},{w:"pension",ko:"연금"},{w:"insurance",ko:"보험"},
{w:"leave",ko:"휴가"},{w:"absence",ko:"결근"},{w:"overtime",ko:"초과 근무"},{w:"shift",ko:"교대 근무"},
{w:"workload",ko:"업무량"},{w:"duty",ko:"임무, 직무"},{w:"responsibility",ko:"책임"},{w:"task",ko:"업무, 과제"},
{w:"assignment",ko:"배정된 일, 과제"},{w:"performance",ko:"실적, 성과"},{w:"evaluation",ko:"평가"},{w:"appraisal",ko:"평가, 사정"},
{w:"supervisor",ko:"감독관, 상사"},{w:"subordinate",ko:"부하 직원"},{w:"colleague",ko:"동료"},{w:"coworker",ko:"동료"},
{w:"department",ko:"부서"},{w:"division",ko:"부서, 사업부"},{w:"executive",ko:"임원"},{w:"director",ko:"이사, 책임자"},
{w:"administrator",ko:"관리자"},{w:"administration",ko:"행정, 관리"},{w:"workshop",ko:"워크숍, 연수"},{w:"seminar",ko:"세미나"},
{w:"training",ko:"교육, 훈련"},{w:"mentor",ko:"멘토, 조언자"},{w:"intern",ko:"인턴"},{w:"internship",ko:"인턴십"},
// 회의·일정 (Meetings / Schedule)
{w:"meeting",ko:"회의"},{w:"conference",ko:"회의, 학회"},{w:"agenda",ko:"안건, 의제"},{w:"minutes",ko:"회의록"},
{w:"attend",ko:"참석하다"},{w:"attendance",ko:"출석"},{w:"attendee",ko:"참석자"},{w:"participant",ko:"참가자"},
{w:"participate",ko:"참여하다"},{w:"presentation",ko:"발표"},{w:"present",ko:"발표하다, 제시하다"},{w:"presenter",ko:"발표자"},
{w:"discuss",ko:"논의하다"},{w:"discussion",ko:"논의"},{w:"review",ko:"검토하다"},{w:"summarize",ko:"요약하다"},
{w:"summary",ko:"요약"},{w:"conclude",ko:"결론짓다"},{w:"conclusion",ko:"결론"},{w:"propose",ko:"제안하다"},
{w:"proposal",ko:"제안(서)"},{w:"suggest",ko:"제안하다"},{w:"suggestion",ko:"제안"},{w:"recommend",ko:"추천하다"},
{w:"recommendation",ko:"추천, 권고"},{w:"decision",ko:"결정"},{w:"approve",ko:"승인하다"},{w:"approval",ko:"승인"},
{w:"reject",ko:"거절하다"},{w:"postpone",ko:"연기하다"},{w:"reschedule",ko:"일정을 변경하다"},{w:"cancel",ko:"취소하다"},
{w:"schedule",ko:"일정(을 잡다)"},{w:"appointment",ko:"약속, 예약"},{w:"arrange",ko:"마련하다, 배치하다"},{w:"arrangement",ko:"준비, 마련"},
{w:"confirm",ko:"확인하다, 확정하다"},{w:"confirmation",ko:"확인"},{w:"notify",ko:"통지하다"},{w:"notification",ko:"통지"},
{w:"announce",ko:"발표하다"},{w:"announcement",ko:"발표, 공지"},{w:"inform",ko:"알리다"},{w:"remind",ko:"상기시키다"},
{w:"reminder",ko:"알림, 메모"},{w:"deadline",ko:"마감 기한"},{w:"due",ko:"기한이 된"},{w:"upcoming",ko:"다가오는"},
{w:"tentative",ko:"잠정적인"},{w:"prompt",ko:"신속한, 즉각적인"},{w:"punctual",ko:"시간을 잘 지키는"},{w:"agenda item",ko:"안건 항목"},
{w:"venue",ko:"장소"},{w:"facilitate",ko:"용이하게 하다"},{w:"chairperson",ko:"의장"},{w:"keynote",ko:"기조연설"},
// 일반 사무 (Office / General)
{w:"document",ko:"문서"},{w:"paperwork",ko:"서류 작업"},{w:"file",ko:"파일, 철하다"},{w:"folder",ko:"폴더"},
{w:"form",ko:"양식"},{w:"report",ko:"보고서"},{w:"memo",ko:"메모, 회람"},{w:"memorandum",ko:"각서, 비망록"},
{w:"draft",ko:"초안"},{w:"copy",ko:"사본, 복사하다"},{w:"duplicate",ko:"복제하다, 사본"},{w:"attachment",ko:"첨부 파일"},
{w:"attach",ko:"첨부하다"},{w:"enclose",ko:"동봉하다"},{w:"enclosed",ko:"동봉된"},{w:"submit",ko:"제출하다"},
{w:"submission",ko:"제출"},{w:"fill out",ko:"작성하다"},{w:"complete",ko:"완료하다, 작성하다"},{w:"sign",ko:"서명하다"},
{w:"signature",ko:"서명"},{w:"stamp",ko:"도장, 우표"},{w:"stationery",ko:"문구류"},{w:"supplies",ko:"비품, 물자"},
{w:"equipment",ko:"장비"},{w:"device",ko:"장치"},{w:"printer",ko:"프린터"},{w:"copier",ko:"복사기"},
{w:"photocopy",ko:"복사하다"},{w:"scanner",ko:"스캐너"},{w:"cabinet",ko:"캐비닛"},{w:"workspace",ko:"작업 공간"},
{w:"cubicle",ko:"칸막이 사무 공간"},{w:"headquarters",ko:"본사"},{w:"branch",ko:"지점"},{w:"subsidiary",ko:"자회사"},
{w:"premises",ko:"건물, 부지"},{w:"reception",ko:"접수처"},{w:"receptionist",ko:"접수 담당자"},{w:"lobby",ko:"로비"},
{w:"colleague",ko:"동료"},{w:"correspondence",ko:"서신 왕래"},{w:"memo board",ko:"게시판"},{w:"bulletin",ko:"게시, 공고"},
{w:"deadline",ko:"기한"},{w:"procedure",ko:"절차"},{w:"process",ko:"과정, 처리하다"},{w:"protocol",ko:"규약, 절차"},
{w:"policy",ko:"정책, 방침"},{w:"guideline",ko:"지침"},{w:"regulation",ko:"규정"},{w:"requirement",ko:"요건"},
{w:"standard",ko:"기준, 표준"},{w:"criterion",ko:"기준"},{w:"objective",ko:"목표"},{w:"goal",ko:"목표"},
{w:"priority",ko:"우선순위"},{w:"efficiency",ko:"효율성"},{w:"productivity",ko:"생산성"},{w:"workflow",ko:"업무 흐름"},
// 마케팅·판매·광고 (Marketing / Sales / Advertising)
{w:"marketing",ko:"마케팅"},{w:"market",ko:"시장"},{w:"advertise",ko:"광고하다"},{w:"advertisement",ko:"광고"},
{w:"advertising",ko:"광고(업)"},{w:"promotion",ko:"판촉, 홍보"},{w:"campaign",ko:"캠페인"},{w:"brand",ko:"상표, 브랜드"},
{w:"product",ko:"제품"},{w:"merchandise",ko:"상품"},{w:"goods",ko:"상품, 물품"},{w:"item",ko:"품목"},
{w:"launch",ko:"출시하다"},{w:"release",ko:"출시, 발표하다"},{w:"introduce",ko:"소개하다, 도입하다"},{w:"feature",ko:"특징, 기능"},
{w:"target",ko:"목표, 대상"},{w:"consumer",ko:"소비자"},{w:"customer",ko:"고객"},{w:"client",ko:"고객, 의뢰인"},
{w:"clientele",ko:"고객층"},{w:"demand",ko:"수요"},{w:"supply",ko:"공급"},{w:"trend",ko:"동향, 추세"},
{w:"survey",ko:"설문 조사"},{w:"questionnaire",ko:"설문지"},{w:"feedback",ko:"피드백, 의견"},{w:"satisfaction",ko:"만족"},
{w:"satisfy",ko:"만족시키다"},{w:"loyalty",ko:"충성도"},{w:"competitor",ko:"경쟁사"},{w:"competition",ko:"경쟁"},
{w:"competitive",ko:"경쟁력 있는"},{w:"strategy",ko:"전략"},{w:"strategic",ko:"전략적인"},{w:"forecast",ko:"예측(하다)"},
{w:"projection",ko:"예상, 추정"},{w:"sales",ko:"판매, 매출"},{w:"revenue",ko:"수익, 매출"},{w:"profit",ko:"이익"},
{w:"profitable",ko:"수익성 있는"},{w:"margin",ko:"이윤, 차익"},{w:"discount",ko:"할인"},{w:"coupon",ko:"쿠폰"},
{w:"voucher",ko:"상품권, 할인권"},{w:"sale",ko:"판매, 할인 판매"},{w:"retail",ko:"소매"},{w:"wholesale",ko:"도매"},
{w:"retailer",ko:"소매업체"},{w:"distributor",ko:"유통업체"},{w:"distribute",ko:"유통하다, 배포하다"},{w:"distribution",ko:"유통, 분배"},
{w:"display",ko:"진열(하다)"},{w:"showroom",ko:"전시장"},{w:"catalog",ko:"카탈로그, 목록"},{w:"brochure",ko:"소책자, 안내서"},
{w:"flyer",ko:"전단지"},{w:"slogan",ko:"표어"},{w:"endorse",ko:"광고에 나오다, 지지하다"},{w:"sponsor",ko:"후원하다, 후원자"},
{w:"exhibition",ko:"전시회"},{w:"booth",ko:"부스"},{w:"trade show",ko:"무역 박람회"},{w:"sample",ko:"견본"},
{w:"demonstration",ko:"시연"},{w:"complimentary",ko:"무료의"},{w:"affordable",ko:"가격이 알맞은"},{w:"premium",ko:"고급의, 할증료"},
{w:"reputation",ko:"평판"},{w:"awareness",ko:"인지도, 인식"},{w:"appeal",ko:"매력, 호소하다"},{w:"persuade",ko:"설득하다"},
// 재무·회계 (Finance / Accounting)
{w:"finance",ko:"재무, 자금"},{w:"financial",ko:"재정의, 금융의"},{w:"accounting",ko:"회계"},{w:"accountant",ko:"회계사"},
{w:"budget",ko:"예산"},{w:"expense",ko:"비용, 경비"},{w:"expenditure",ko:"지출"},{w:"cost",ko:"비용"},
{w:"income",ko:"소득"},{w:"earnings",ko:"수익, 소득"},{w:"asset",ko:"자산"},{w:"liability",ko:"부채"},
{w:"debt",ko:"빚, 부채"},{w:"capital",ko:"자본"},{w:"fund",ko:"자금"},{w:"funding",ko:"자금 지원"},
{w:"invest",ko:"투자하다"},{w:"investment",ko:"투자"},{w:"investor",ko:"투자자"},{w:"stock",ko:"주식, 재고"},
{w:"share",ko:"주식, 몫"},{w:"shareholder",ko:"주주"},{w:"dividend",ko:"배당금"},{w:"interest",ko:"이자, 이익"},
{w:"loan",ko:"대출"},{w:"mortgage",ko:"담보 대출"},{w:"credit",ko:"신용, 외상"},{w:"deposit",ko:"예금, 보증금"},
{w:"withdraw",ko:"인출하다"},{w:"withdrawal",ko:"인출"},{w:"transaction",ko:"거래"},{w:"balance",ko:"잔액, 균형"},
{w:"statement",ko:"명세서, 진술"},{w:"invoice",ko:"송장, 청구서"},{w:"bill",ko:"청구서, 계산서"},{w:"receipt",ko:"영수증"},
{w:"payment",ko:"지불, 납입"},{w:"installment",ko:"할부(금)"},{w:"refund",ko:"환불(하다)"},{w:"reimburse",ko:"상환하다"},
{w:"reimbursement",ko:"상환, 변제"},{w:"audit",ko:"회계 감사"},{w:"auditor",ko:"감사관"},{w:"taxation",ko:"과세"},
{w:"tax",ko:"세금"},{w:"deduct",ko:"공제하다"},{w:"deduction",ko:"공제"},{w:"fiscal",ko:"재정의, 회계의"},
{w:"quarter",ko:"분기"},{w:"quarterly",ko:"분기별의"},{w:"annual",ko:"연간의"},{w:"net",ko:"순(純)"},
{w:"gross",ko:"총(總)"},{w:"surplus",ko:"흑자, 잉여"},{w:"deficit",ko:"적자"},{w:"currency",ko:"통화"},
{w:"exchange rate",ko:"환율"},{w:"inflation",ko:"물가 상승"},{w:"recession",ko:"경기 침체"},{w:"economy",ko:"경제"},
{w:"economic",ko:"경제의"},{w:"valuation",ko:"평가, 가치 산정"},{w:"estimate",ko:"견적, 추정하다"},{w:"figure",ko:"수치, 숫자"},
// 계약·법무 (Contracts / Legal)
{w:"contract",ko:"계약(서)"},{w:"agreement",ko:"합의, 계약"},{w:"deal",ko:"거래, 계약"},{w:"negotiate",ko:"협상하다"},
{w:"negotiation",ko:"협상"},{w:"terms",ko:"조건, 조항"},{w:"clause",ko:"조항"},{w:"provision",ko:"조항, 규정"},
{w:"condition",ko:"조건"},{w:"obligation",ko:"의무"},{w:"liable",ko:"책임이 있는"},{w:"binding",ko:"구속력 있는"},
{w:"valid",ko:"유효한"},{w:"void",ko:"무효의"},{w:"expire",ko:"만료되다"},{w:"expiration",ko:"만료"},
{w:"renew",ko:"갱신하다"},{w:"renewal",ko:"갱신"},{w:"extend",ko:"연장하다"},{w:"extension",ko:"연장, 내선"},
{w:"amend",ko:"수정하다"},{w:"amendment",ko:"수정안"},{w:"revise",ko:"수정하다"},{w:"revision",ko:"수정"},
{w:"breach",ko:"위반"},{w:"violate",ko:"위반하다"},{w:"violation",ko:"위반"},{w:"comply",ko:"준수하다"},
{w:"compliance",ko:"준수"},{w:"enforce",ko:"시행하다, 집행하다"},{w:"penalty",ko:"위약금, 벌금"},{w:"fine",ko:"벌금"},
{w:"warranty",ko:"품질 보증"},{w:"guarantee",ko:"보증(하다)"},{w:"liability",ko:"법적 책임"},{w:"lawsuit",ko:"소송"},
{w:"sue",ko:"고소하다"},{w:"attorney",ko:"변호사"},{w:"legal",ko:"법적인"},{w:"legislation",ko:"법률, 입법"},
{w:"intellectual property",ko:"지식 재산권"},{w:"patent",ko:"특허"},{w:"copyright",ko:"저작권"},{w:"trademark",ko:"상표권"},
{w:"confidential",ko:"기밀의"},{w:"disclose",ko:"공개하다, 폭로하다"},{w:"disclosure",ko:"공개"},{w:"waiver",ko:"포기, 면제"},
{w:"settlement",ko:"합의, 정산"},{w:"arbitration",ko:"중재"},{w:"jurisdiction",ko:"관할권"},{w:"draft",ko:"초안을 작성하다"},
// 생산·제조 (Manufacturing / Production)
{w:"manufacture",ko:"제조하다"},{w:"manufacturer",ko:"제조업체"},{w:"production",ko:"생산"},{w:"produce",ko:"생산하다"},
{w:"factory",ko:"공장"},{w:"plant",ko:"공장"},{w:"facility",ko:"시설"},{w:"assembly",ko:"조립"},
{w:"assemble",ko:"조립하다"},{w:"machinery",ko:"기계류"},{w:"equipment",ko:"장비"},{w:"operate",ko:"가동하다, 운영하다"},
{w:"operation",ko:"운영, 작동"},{w:"capacity",ko:"용량, 생산 능력"},{w:"output",ko:"생산량"},{w:"input",ko:"투입"},
{w:"material",ko:"재료"},{w:"raw material",ko:"원자재"},{w:"component",ko:"부품, 구성 요소"},{w:"part",ko:"부품"},
{w:"unit",ko:"단위, 한 개"},{w:"batch",ko:"한 회분, 묶음"},{w:"defect",ko:"결함"},{w:"defective",ko:"결함이 있는"},
{w:"flaw",ko:"결함, 흠"},{w:"quality control",ko:"품질 관리"},{w:"inspect",ko:"점검하다"},{w:"inspection",ko:"점검"},
{w:"inspector",ko:"검사관"},{w:"maintenance",ko:"유지 보수"},{w:"maintain",ko:"유지하다"},{w:"repair",ko:"수리(하다)"},
{w:"malfunction",ko:"오작동"},{w:"breakdown",ko:"고장"},{w:"shutdown",ko:"가동 중단"},{w:"safety",ko:"안전"},
{w:"hazard",ko:"위험 요소"},{w:"caution",ko:"주의"},{w:"precaution",ko:"예방 조치"},{w:"specification",ko:"사양, 명세"},
{w:"prototype",ko:"시제품"},{w:"durable",ko:"내구성 있는"},{w:"durability",ko:"내구성"},{w:"efficient",ko:"효율적인"},
// 물류·배송·구매 (Logistics / Shipping / Purchasing)
{w:"logistics",ko:"물류"},{w:"shipment",ko:"수송, 적하물"},{w:"ship",ko:"발송하다"},{w:"shipping",ko:"배송, 운송"},
{w:"deliver",ko:"배달하다"},{w:"delivery",ko:"배달"},{w:"freight",ko:"화물(운송)"},{w:"cargo",ko:"화물"},
{w:"carrier",ko:"운송업체"},{w:"transport",ko:"운송하다"},{w:"transportation",ko:"운송, 교통"},{w:"warehouse",ko:"창고"},
{w:"inventory",ko:"재고(품)"},{w:"stock",ko:"재고"},{w:"in stock",ko:"재고가 있는"},{w:"out of stock",ko:"품절된"},
{w:"restock",ko:"다시 채우다"},{w:"supply chain",ko:"공급망"},{w:"supplier",ko:"공급업체"},{w:"vendor",ko:"판매업체"},
{w:"procurement",ko:"조달"},{w:"purchase",ko:"구매(하다)"},{w:"purchasing",ko:"구매(업무)"},{w:"order",ko:"주문(하다)"},
{w:"backorder",ko:"이월 주문"},{w:"quantity",ko:"수량"},{w:"bulk",ko:"대량"},{w:"package",ko:"소포, 포장"},
{w:"packaging",ko:"포장(재)"},{w:"parcel",ko:"소포"},{w:"label",ko:"라벨, 표"},{w:"track",ko:"추적하다"},
{w:"tracking",ko:"추적"},{w:"dispatch",ko:"발송하다"},{w:"forward",ko:"전달하다, 보내다"},{w:"customs",ko:"세관"},
{w:"tariff",ko:"관세"},{w:"export",ko:"수출(하다)"},{w:"import",ko:"수입(하다)"},{w:"handling",ko:"취급, 처리"},
{w:"fragile",ko:"깨지기 쉬운"},{w:"loading",ko:"적재"},{w:"unload",ko:"짐을 내리다"},{w:"fleet",ko:"(차량) 무리, 선단"},
// 출장·여행·숙박 (Business Trip / Travel / Hotel)
{w:"business trip",ko:"출장"},{w:"itinerary",ko:"여행 일정표"},{w:"destination",ko:"목적지"},{w:"departure",ko:"출발"},
{w:"depart",ko:"출발하다"},{w:"arrival",ko:"도착"},{w:"boarding",ko:"탑승"},{w:"board",ko:"탑승하다"},
{w:"flight",ko:"항공편"},{w:"airline",ko:"항공사"},{w:"airfare",ko:"항공 요금"},{w:"layover",ko:"경유, 도중 체류"},
{w:"connecting flight",ko:"연결 항공편"},{w:"delay",ko:"지연(시키다)"},{w:"cancellation",ko:"취소"},{w:"baggage",ko:"수하물"},
{w:"luggage",ko:"짐"},{w:"carry-on",ko:"기내 휴대 수하물"},{w:"customs",ko:"세관"},{w:"immigration",ko:"출입국 심사"},
{w:"passport",ko:"여권"},{w:"visa",ko:"비자"},{w:"boarding pass",ko:"탑승권"},{w:"terminal",ko:"터미널"},
{w:"reservation",ko:"예약"},{w:"reserve",ko:"예약하다"},{w:"book",ko:"예약하다"},{w:"booking",ko:"예약"},
{w:"accommodation",ko:"숙박 시설"},{w:"lodging",ko:"숙소"},{w:"check-in",ko:"체크인"},{w:"check-out",ko:"체크아웃"},
{w:"vacancy",ko:"빈 객실"},{w:"suite",ko:"스위트룸"},{w:"amenity",ko:"편의 시설"},{w:"concierge",ko:"안내원"},
{w:"rate",ko:"요금, 비율"},{w:"fare",ko:"운임, 요금"},{w:"toll",ko:"통행료"},{w:"rental",ko:"대여"},
{w:"rent",ko:"임대하다, 빌리다"},{w:"shuttle",ko:"셔틀(버스)"},{w:"tourism",ko:"관광(업)"},{w:"tourist",ko:"관광객"},
{w:"sightseeing",ko:"관광"},{w:"excursion",ko:"짧은 여행"},{w:"souvenir",ko:"기념품"},{w:"complimentary",ko:"무료 제공의"},
// 부동산·시설 (Real Estate / Facilities)
{w:"property",ko:"부동산, 재산"},{w:"real estate",ko:"부동산"},{w:"lease",ko:"임대차 계약"},{w:"tenant",ko:"세입자"},
{w:"landlord",ko:"집주인"},{w:"rent",ko:"임대료"},{w:"deposit",ko:"보증금"},{w:"furnished",ko:"가구가 비치된"},
{w:"vacant",ko:"비어 있는"},{w:"occupy",ko:"차지하다, 사용하다"},{w:"occupant",ko:"입주자"},{w:"resident",ko:"거주자"},
{w:"residential",ko:"주거의"},{w:"commercial",ko:"상업의"},{w:"premises",ko:"부지, 건물"},{w:"renovate",ko:"개조하다"},
{w:"renovation",ko:"개조"},{w:"remodel",ko:"개조하다"},{w:"construct",ko:"건설하다"},{w:"construction",ko:"건설"},
{w:"architect",ko:"건축가"},{w:"contractor",ko:"도급업자"},{w:"blueprint",ko:"설계도"},{w:"site",ko:"현장, 부지"},
{w:"square footage",ko:"면적"},{w:"floor plan",ko:"평면도"},{w:"utility",ko:"공공요금, 설비"},{w:"appliance",ko:"가전제품"},
{w:"installation",ko:"설치"},{w:"install",ko:"설치하다"},{w:"plumbing",ko:"배관"},{w:"ventilation",ko:"환기"},
{w:"furnish",ko:"비치하다"},{w:"spacious",ko:"넓은"},{w:"accessible",ko:"접근 가능한"},{w:"located",ko:"위치한"},
{w:"relocate",ko:"이전하다"},{w:"relocation",ko:"이전"},{w:"premise",ko:"전제"},{w:"janitor",ko:"관리인, 청소부"},
// 고객 서비스·문의 (Customer Service)
{w:"service",ko:"서비스"},{w:"customer service",ko:"고객 서비스"},{w:"inquiry",ko:"문의"},{w:"inquire",ko:"문의하다"},
{w:"request",ko:"요청(하다)"},{w:"complaint",ko:"불만"},{w:"complain",ko:"불평하다"},{w:"issue",ko:"문제, 사안"},
{w:"resolve",ko:"해결하다"},{w:"solution",ko:"해결책"},{w:"assist",ko:"돕다"},{w:"assistance",ko:"도움"},
{w:"support",ko:"지원(하다)"},{w:"handle",ko:"처리하다"},{w:"address",ko:"(문제를) 다루다"},{w:"respond",ko:"응답하다"},
{w:"response",ko:"응답"},{w:"reply",ko:"답장(하다)"},{w:"satisfied",ko:"만족한"},{w:"dissatisfied",ko:"불만족한"},
{w:"apologize",ko:"사과하다"},{w:"apology",ko:"사과"},{w:"replacement",ko:"교체(품)"},{w:"replace",ko:"교체하다"},
{w:"exchange",ko:"교환(하다)"},{w:"return",ko:"반품(하다)"},{w:"defect",ko:"하자"},{w:"compensate",ko:"보상하다"},
{w:"courteous",ko:"정중한"},{w:"helpline",ko:"상담 전화"},{w:"hotline",ko:"직통 전화"},{w:"representative",ko:"담당 직원, 대표"},
{w:"agent",ko:"대리인, 직원"},{w:"membership",ko:"회원(자격)"},{w:"subscribe",ko:"구독하다"},{w:"subscription",ko:"구독"},
// IT·기술 (Technology / IT)
{w:"technology",ko:"기술"},{w:"technical",ko:"기술적인"},{w:"software",ko:"소프트웨어"},{w:"hardware",ko:"하드웨어"},
{w:"update",ko:"갱신, 업데이트"},{w:"upgrade",ko:"향상시키다"},{w:"install",ko:"설치하다"},{w:"download",ko:"내려받다"},
{w:"upload",ko:"올리다"},{w:"network",ko:"네트워크, 인맥"},{w:"server",ko:"서버"},{w:"database",ko:"데이터베이스"},
{w:"data",ko:"자료, 데이터"},{w:"access",ko:"접근(하다)"},{w:"backup",ko:"백업"},{w:"restore",ko:"복구하다"},
{w:"crash",ko:"고장 나다, 충돌"},{w:"glitch",ko:"오류, 결함"},{w:"troubleshoot",ko:"문제를 해결하다"},{w:"compatible",ko:"호환되는"},
{w:"function",ko:"기능"},{w:"feature",ko:"기능, 특징"},{w:"interface",ko:"인터페이스"},{w:"platform",ko:"플랫폼"},
{w:"automate",ko:"자동화하다"},{w:"automatic",ko:"자동의"},{w:"digital",ko:"디지털의"},{w:"encryption",ko:"암호화"},
{w:"security",ko:"보안"},{w:"password",ko:"비밀번호"},{w:"login",ko:"로그인"},{w:"setting",ko:"설정"},
// 빈출 동사 (Common Verbs)
{w:"acquire",ko:"얻다, 인수하다"},{w:"obtain",ko:"얻다"},{w:"achieve",ko:"달성하다"},{w:"accomplish",ko:"성취하다"},
{w:"establish",ko:"설립하다, 확립하다"},{w:"found",ko:"설립하다"},{w:"expand",ko:"확장하다"},{w:"increase",ko:"증가하다"},
{w:"decrease",ko:"감소하다"},{w:"reduce",ko:"줄이다"},{w:"decline",ko:"감소하다, 거절하다"},{w:"improve",ko:"개선하다"},
{w:"enhance",ko:"향상시키다"},{w:"boost",ko:"끌어올리다"},{w:"maximize",ko:"극대화하다"},{w:"minimize",ko:"최소화하다"},
{w:"implement",ko:"시행하다"},{w:"execute",ko:"실행하다"},{w:"conduct",ko:"수행하다, 실시하다"},{w:"perform",ko:"수행하다"},
{w:"undertake",ko:"착수하다"},{w:"pursue",ko:"추구하다"},{w:"determine",ko:"결정하다, 알아내다"},{w:"identify",ko:"확인하다, 식별하다"},
{w:"indicate",ko:"나타내다"},{w:"demonstrate",ko:"보여주다, 입증하다"},{w:"illustrate",ko:"설명하다, 예시하다"},{w:"clarify",ko:"명확히 하다"},
{w:"specify",ko:"명시하다"},{w:"highlight",ko:"강조하다"},{w:"emphasize",ko:"강조하다"},{w:"stress",ko:"강조하다"},
{w:"ensure",ko:"보장하다"},{w:"guarantee",ko:"보장하다"},{w:"verify",ko:"확인하다, 입증하다"},{w:"examine",ko:"검사하다"},
{w:"evaluate",ko:"평가하다"},{w:"assess",ko:"평가하다"},{w:"analyze",ko:"분석하다"},{w:"measure",ko:"측정하다"},
{w:"calculate",ko:"계산하다"},{w:"estimate",ko:"추정하다"},{w:"predict",ko:"예측하다"},{w:"anticipate",ko:"예상하다"},
{w:"assume",ko:"가정하다, 추정하다"},{w:"consider",ko:"고려하다"},{w:"regard",ko:"여기다, 간주하다"},{w:"recognize",ko:"인정하다, 알아보다"},
{w:"acknowledge",ko:"인정하다"},{w:"admit",ko:"인정하다"},{w:"deny",ko:"부인하다"},{w:"declare",ko:"선언하다, 신고하다"},
{w:"state",ko:"진술하다"},{w:"mention",ko:"언급하다"},{w:"refer",ko:"언급하다, 참조하다"},{w:"address",ko:"연설하다"},
{w:"assign",ko:"배정하다"},{w:"allocate",ko:"할당하다"},{w:"designate",ko:"지정하다"},{w:"appoint",ko:"임명하다"},
{w:"nominate",ko:"지명하다"},{w:"select",ko:"선정하다"},{w:"appoint",ko:"임명하다"},{w:"delegate",ko:"위임하다"},
{w:"authorize",ko:"권한을 주다"},{w:"permit",ko:"허가하다"},{w:"prohibit",ko:"금지하다"},{w:"restrict",ko:"제한하다"},
{w:"limit",ko:"제한하다"},{w:"prevent",ko:"막다, 예방하다"},{w:"avoid",ko:"피하다"},{w:"eliminate",ko:"제거하다"},
{w:"remove",ko:"제거하다"},{w:"resolve",ko:"해결하다"},{w:"settle",ko:"해결하다, 정착하다"},{w:"overcome",ko:"극복하다"},
{w:"adopt",ko:"채택하다"},{w:"adapt",ko:"적응시키다"},{w:"adjust",ko:"조정하다"},{w:"modify",ko:"수정하다"},
{w:"convert",ko:"전환하다"},{w:"transform",ko:"변형하다"},{w:"replace",ko:"대체하다"},{w:"substitute",ko:"대체하다"},
{w:"combine",ko:"결합하다"},{w:"integrate",ko:"통합하다"},{w:"merge",ko:"합병하다"},{w:"separate",ko:"분리하다"},
{w:"divide",ko:"나누다"},{w:"split",ko:"나누다"},{w:"contribute",ko:"기여하다"},{w:"participate",ko:"참여하다"},
{w:"collaborate",ko:"협력하다"},{w:"cooperate",ko:"협력하다"},{w:"coordinate",ko:"조정하다"},{w:"facilitate",ko:"촉진하다"},
{w:"encourage",ko:"격려하다"},{w:"motivate",ko:"동기를 부여하다"},{w:"inspire",ko:"영감을 주다"},{w:"persuade",ko:"설득하다"},
{w:"convince",ko:"확신시키다"},{w:"influence",ko:"영향을 주다"},{w:"impact",ko:"영향을 주다"},{w:"affect",ko:"영향을 미치다"},
{w:"benefit",ko:"이익을 주다"},{w:"contribute to",ko:"~에 기여하다"},{w:"depend on",ko:"~에 의존하다"},{w:"rely on",ko:"~에 의지하다"},
{w:"consist of",ko:"~으로 구성되다"},{w:"comprise",ko:"구성하다"},{w:"feature",ko:"특징으로 하다"},{w:"involve",ko:"수반하다, 포함하다"},
// 빈출 형용사 (Common Adjectives)
{w:"available",ko:"이용 가능한"},{w:"unavailable",ko:"이용할 수 없는"},{w:"accessible",ko:"접근 가능한"},{w:"appropriate",ko:"적절한"},
{w:"suitable",ko:"적합한"},{w:"adequate",ko:"충분한, 적절한"},{w:"sufficient",ko:"충분한"},{w:"essential",ko:"필수적인"},
{w:"crucial",ko:"중대한"},{w:"vital",ko:"필수적인"},{w:"significant",ko:"중요한, 상당한"},{w:"considerable",ko:"상당한"},
{w:"substantial",ko:"상당한"},{w:"numerous",ko:"수많은"},{w:"various",ko:"다양한"},{w:"diverse",ko:"다양한"},
{w:"multiple",ko:"다수의"},{w:"additional",ko:"추가의"},{w:"extra",ko:"추가의"},{w:"complimentary",ko:"무료의"},
{w:"complementary",ko:"상호 보완적인"},{w:"mandatory",ko:"의무적인"},{w:"compulsory",ko:"의무적인"},{w:"optional",ko:"선택적인"},
{w:"voluntary",ko:"자발적인"},{w:"eligible",ko:"자격이 있는"},{w:"reliable",ko:"믿을 만한"},{w:"dependable",ko:"믿을 수 있는"},
{w:"consistent",ko:"일관된"},{w:"stable",ko:"안정적인"},{w:"flexible",ko:"융통성 있는"},{w:"comprehensive",ko:"종합적인"},
{w:"thorough",ko:"철저한"},{w:"detailed",ko:"상세한"},{w:"accurate",ko:"정확한"},{w:"precise",ko:"정밀한"},
{w:"exact",ko:"정확한"},{w:"prompt",ko:"신속한"},{w:"efficient",ko:"효율적인"},{w:"effective",ko:"효과적인"},
{w:"productive",ko:"생산적인"},{w:"profitable",ko:"수익성 있는"},{w:"feasible",ko:"실행 가능한"},{w:"viable",ko:"실행 가능한"},
{w:"prospective",ko:"장래의, 유망한"},{w:"potential",ko:"잠재적인"},{w:"current",ko:"현재의"},{w:"existing",ko:"기존의"},
{w:"previous",ko:"이전의"},{w:"former",ko:"이전의"},{w:"latter",ko:"후자의"},{w:"subsequent",ko:"그 다음의"},
{w:"consecutive",ko:"연속적인"},{w:"temporary",ko:"임시의"},{w:"permanent",ko:"영구적인"},{w:"initial",ko:"처음의"},
{w:"preliminary",ko:"예비의"},{w:"final",ko:"최종의"},{w:"ultimate",ko:"궁극적인"},{w:"overall",ko:"전반적인"},
{w:"entire",ko:"전체의"},{w:"complete",ko:"완전한"},{w:"partial",ko:"부분적인"},{w:"specific",ko:"구체적인"},
{w:"general",ko:"일반적인"},{w:"particular",ko:"특정한"},{w:"relevant",ko:"관련 있는"},{w:"related",ko:"관련된"},
{w:"familiar",ko:"익숙한"},{w:"complicated",ko:"복잡한"},{w:"complex",ko:"복잡한"},{w:"simple",ko:"간단한"},
// 경영·전략 (Management / Strategy)
{w:"management",ko:"경영, 관리"},{w:"manage",ko:"관리하다"},{w:"corporation",ko:"기업"},{w:"corporate",ko:"기업의"},
{w:"enterprise",ko:"기업, 사업"},{w:"firm",ko:"회사"},{w:"organization",ko:"조직"},{w:"institution",ko:"기관"},
{w:"venture",ko:"벤처, 모험적 사업"},{w:"startup",ko:"신생 기업"},{w:"partnership",ko:"동업, 제휴"},{w:"alliance",ko:"제휴, 동맹"},
{w:"merger",ko:"합병"},{w:"acquisition",ko:"인수"},{w:"takeover",ko:"기업 인수"},{w:"restructure",ko:"구조 조정하다"},
{w:"expansion",ko:"확장"},{w:"growth",ko:"성장"},{w:"development",ko:"개발, 발전"},{w:"initiative",ko:"계획, 주도권"},
{w:"venture",ko:"사업"},{w:"mission",ko:"임무, 사명"},{w:"vision",ko:"비전"},{w:"objective",ko:"목표"},
{w:"milestone",ko:"이정표, 중대 시점"},{w:"benchmark",ko:"기준점"},{w:"outcome",ko:"결과"},{w:"achievement",ko:"성취"},
{w:"leadership",ko:"리더십"},{w:"authority",ko:"권한, 당국"},{w:"hierarchy",ko:"위계 질서"},{w:"governance",ko:"지배 구조"},
{w:"stakeholder",ko:"이해관계자"},{w:"board",ko:"이사회"},{w:"committee",ko:"위원회"},{w:"council",ko:"협의회"},
{w:"chairman",ko:"의장, 회장"},{w:"founder",ko:"창립자"},{w:"entrepreneur",ko:"기업가"},{w:"delegate",ko:"대표, 위임하다"},
{w:"oversee",ko:"감독하다"},{w:"supervise",ko:"감독하다"},{w:"monitor",ko:"감시하다"},{w:"streamline",ko:"간소화하다"},
{w:"outsource",ko:"외부에 위탁하다"},{w:"downsize",ko:"규모를 줄이다"},{w:"consolidate",ko:"통합하다"},{w:"diversify",ko:"다각화하다"},
// 회사 행사·활동
{w:"ceremony",ko:"의식, 식"},{w:"celebration",ko:"축하 행사"},{w:"anniversary",ko:"기념일"},{w:"banquet",ko:"연회"},
{w:"reception",ko:"환영회"},{w:"gathering",ko:"모임"},{w:"gala",ko:"경축 행사"},{w:"fundraiser",ko:"모금 행사"},
{w:"award",ko:"상"},{w:"recognition",ko:"인정, 표창"},{w:"honor",ko:"명예, 영예를 주다"},{w:"achievement",ko:"업적"},
{w:"retreat",ko:"수련회"},{w:"outing",ko:"야유회"},{w:"volunteer",ko:"자원봉사(자)"},{w:"charity",ko:"자선"},
{w:"donation",ko:"기부"},{w:"donate",ko:"기부하다"},{w:"contribution",ko:"기여, 기부"},{w:"community",ko:"지역 사회"},
// 환경·에너지
{w:"environment",ko:"환경"},{w:"environmental",ko:"환경의"},{w:"sustainable",ko:"지속 가능한"},{w:"sustainability",ko:"지속 가능성"},
{w:"renewable",ko:"재생 가능한"},{w:"recycle",ko:"재활용하다"},{w:"recycling",ko:"재활용"},{w:"conservation",ko:"보존"},
{w:"conserve",ko:"아끼다, 보존하다"},{w:"emission",ko:"배출(물)"},{w:"pollution",ko:"오염"},{w:"pollutant",ko:"오염 물질"},
{w:"waste",ko:"폐기물, 낭비"},{w:"energy",ko:"에너지"},{w:"efficiency",ko:"효율"},{w:"resource",ko:"자원"},
{w:"natural resource",ko:"천연자원"},{w:"climate",ko:"기후"},{w:"ecosystem",ko:"생태계"},{w:"eco-friendly",ko:"친환경적인"},
{w:"green",ko:"친환경의"},{w:"solar",ko:"태양의"},{w:"carbon",ko:"탄소"},{w:"footprint",ko:"발자국, 영향"},
// 미디어·출판·홍보
{w:"media",ko:"매체"},{w:"press",ko:"언론"},{w:"journalist",ko:"기자"},{w:"reporter",ko:"기자"},
{w:"article",ko:"기사"},{w:"editorial",ko:"사설"},{w:"editor",ko:"편집자"},{w:"publication",ko:"출판(물)"},
{w:"publish",ko:"출판하다"},{w:"publisher",ko:"출판사"},{w:"issue",ko:"발행(호)"},{w:"edition",ko:"판"},
{w:"circulation",ko:"발행 부수"},{w:"subscriber",ko:"구독자"},{w:"broadcast",ko:"방송(하다)"},{w:"coverage",ko:"보도, 취재"},
{w:"interview",ko:"인터뷰"},{w:"statement",ko:"성명"},{w:"spokesperson",ko:"대변인"},{w:"public relations",ko:"홍보"},
{w:"publicity",ko:"홍보, 평판"},{w:"release",ko:"보도 자료, 발표"},{w:"headline",ko:"표제"},{w:"column",ko:"칼럼, 단"},
// 부사 (Common Adverbs)
{w:"approximately",ko:"대략"},{w:"roughly",ko:"대략"},{w:"nearly",ko:"거의"},{w:"barely",ko:"간신히, 거의 ~않다"},
{w:"hardly",ko:"거의 ~않다"},{w:"relatively",ko:"비교적"},{w:"considerably",ko:"상당히"},{w:"significantly",ko:"상당히"},
{w:"slightly",ko:"약간"},{w:"extremely",ko:"극도로"},{w:"highly",ko:"매우"},{w:"entirely",ko:"완전히"},
{w:"completely",ko:"완전히"},{w:"thoroughly",ko:"철저히"},{w:"mainly",ko:"주로"},{w:"primarily",ko:"주로"},
{w:"mostly",ko:"대부분"},{w:"largely",ko:"대체로"},{w:"particularly",ko:"특히"},{w:"especially",ko:"특히"},
{w:"specifically",ko:"구체적으로"},{w:"generally",ko:"일반적으로"},{w:"typically",ko:"일반적으로"},{w:"normally",ko:"보통"},
{w:"regularly",ko:"정기적으로"},{w:"frequently",ko:"자주"},{w:"occasionally",ko:"가끔"},{w:"rarely",ko:"드물게"},
{w:"immediately",ko:"즉시"},{w:"promptly",ko:"즉시"},{w:"shortly",ko:"곧"},{w:"currently",ko:"현재"},
{w:"recently",ko:"최근에"},{w:"previously",ko:"이전에"},{w:"subsequently",ko:"그 후에"},{w:"eventually",ko:"결국"},
{w:"temporarily",ko:"일시적으로"},{w:"permanently",ko:"영구적으로"},{w:"accordingly",ko:"그에 따라"},{w:"consequently",ko:"결과적으로"},
{w:"therefore",ko:"그러므로"},{w:"however",ko:"그러나"},{w:"nevertheless",ko:"그럼에도 불구하고"},{w:"furthermore",ko:"게다가"},
{w:"moreover",ko:"게다가"},{w:"additionally",ko:"추가로"},{w:"otherwise",ko:"그렇지 않으면"},{w:"meanwhile",ko:"그 동안에"},
// 의료·보험·복지
{w:"medical",ko:"의료의"},{w:"clinic",ko:"진료소"},{w:"physician",ko:"내과 의사"},{w:"surgeon",ko:"외과 의사"},
{w:"patient",ko:"환자"},{w:"treatment",ko:"치료"},{w:"treat",ko:"치료하다"},{w:"diagnosis",ko:"진단"},
{w:"diagnose",ko:"진단하다"},{w:"prescription",ko:"처방(전)"},{w:"prescribe",ko:"처방하다"},{w:"pharmacy",ko:"약국"},
{w:"pharmacist",ko:"약사"},{w:"dosage",ko:"복용량"},{w:"symptom",ko:"증상"},{w:"checkup",ko:"건강 검진"},
{w:"vaccination",ko:"예방 접종"},{w:"emergency",ko:"비상사태, 응급"},{w:"ambulance",ko:"구급차"},{w:"recovery",ko:"회복"},
{w:"recover",ko:"회복하다"},{w:"surgery",ko:"수술"},{w:"therapy",ko:"치료, 요법"},{w:"wellness",ko:"건강"},
{w:"coverage",ko:"보장 범위"},{w:"premium",ko:"보험료"},{w:"claim",ko:"청구(하다), 주장"},{w:"policyholder",ko:"보험 계약자"},
{w:"beneficiary",ko:"수혜자"},{w:"deductible",ko:"공제액"},{w:"underwrite",ko:"보험을 인수하다"},{w:"welfare",ko:"복지"},
// 비즈니스 기타 명사·표현
{w:"opportunity",ko:"기회"},{w:"advantage",ko:"이점"},{w:"disadvantage",ko:"단점"},{w:"drawback",ko:"결점"},
{w:"challenge",ko:"도전, 어려움"},{w:"obstacle",ko:"장애물"},{w:"difficulty",ko:"어려움"},{w:"concern",ko:"우려, 관심사"},
{w:"risk",ko:"위험"},{w:"threat",ko:"위협"},{w:"crisis",ko:"위기"},{w:"emergency",ko:"긴급 상황"},
{w:"solution",ko:"해결책"},{w:"approach",ko:"접근법"},{w:"method",ko:"방법"},{w:"technique",ko:"기법"},
{w:"aspect",ko:"측면"},{w:"factor",ko:"요인"},{w:"element",ko:"요소"},{w:"component",ko:"구성 요소"},
{w:"feature",ko:"특징"},{w:"characteristic",ko:"특성"},{w:"trait",ko:"특성"},{w:"property",ko:"속성"},
{w:"quality",ko:"품질, 자질"},{w:"quantity",ko:"양"},{w:"amount",ko:"양, 액수"},{w:"volume",ko:"양, 용량"},
{w:"proportion",ko:"비율"},{w:"ratio",ko:"비율"},{w:"percentage",ko:"비율, 백분율"},{w:"average",ko:"평균"},
{w:"maximum",ko:"최대"},{w:"minimum",ko:"최소"},{w:"limit",ko:"한계"},{w:"range",ko:"범위"},
{w:"scope",ko:"범위"},{w:"scale",ko:"규모, 척도"},{w:"extent",ko:"정도, 범위"},{w:"degree",ko:"정도"},
{w:"level",ko:"수준"},{w:"rate",ko:"비율, 속도"},{w:"frequency",ko:"빈도"},{w:"duration",ko:"기간"},
{w:"period",ko:"기간"},{w:"interval",ko:"간격"},{w:"phase",ko:"단계"},{w:"stage",ko:"단계"},
{w:"step",ko:"단계"},{w:"procedure",ko:"절차"},{w:"sequence",ko:"순서"},{w:"order",ko:"순서"},
{w:"category",ko:"범주"},{w:"classification",ko:"분류"},{w:"type",ko:"유형"},{w:"version",ko:"버전, 판"},
{w:"alternative",ko:"대안"},{w:"option",ko:"선택권"},{w:"choice",ko:"선택"},{w:"preference",ko:"선호"},
{w:"requirement",ko:"요건"},{w:"prerequisite",ko:"전제 조건"},{w:"qualification",ko:"자격"},{w:"credential",ko:"자격증"},
{w:"certificate",ko:"증명서"},{w:"certification",ko:"인증"},{w:"license",ko:"면허"},{w:"permit",ko:"허가증"},
{w:"registration",ko:"등록"},{w:"register",ko:"등록하다"},{w:"enrollment",ko:"등록, 입학"},{w:"enroll",ko:"등록하다"},
{w:"application",ko:"신청(서), 적용"},{w:"apply",ko:"신청하다, 적용하다"},{w:"applicable",ko:"적용 가능한"},{w:"approval",ko:"승인"},
{w:"authorization",ko:"인가"},{w:"permission",ko:"허가"},{w:"consent",ko:"동의"},{w:"endorsement",ko:"지지, 보증"},
{w:"reference number",ko:"참조 번호"},{w:"identification",ko:"신분 증명"},{w:"verification",ko:"확인, 입증"},{w:"validation",ko:"유효성 확인"},
{w:"estimate",ko:"견적"},{w:"quote",ko:"견적(을 내다)"},{w:"quotation",ko:"견적서, 인용"},{w:"proposal",ko:"제안서"},
{w:"bid",ko:"입찰"},{w:"tender",ko:"입찰"},{w:"contract",ko:"계약"},{w:"commitment",ko:"약속, 헌신"},
{w:"obligation",ko:"의무"},{w:"liability",ko:"책임"},{w:"accountability",ko:"책임"},{w:"transparency",ko:"투명성"},
{w:"integrity",ko:"진실성, 무결성"},{w:"reliability",ko:"신뢰성"},{w:"credibility",ko:"신뢰성"},{w:"reputation",ko:"평판"},
{w:"profile",ko:"개요, 프로필"},{w:"portfolio",ko:"포트폴리오"},{w:"resume",ko:"이력서"},{w:"biography",ko:"약력"},
{w:"expertise",ko:"전문 지식"},{w:"specialist",ko:"전문가"},{w:"professional",ko:"전문가, 전문적인"},{w:"amateur",ko:"아마추어"},
{w:"competence",ko:"능력"},{w:"capability",ko:"역량"},{w:"capacity",ko:"능력, 수용력"},{w:"potential",ko:"잠재력"},
{w:"skill",ko:"기술, 솜씨"},{w:"talent",ko:"재능"},{w:"ability",ko:"능력"},{w:"aptitude",ko:"적성"},
{w:"productivity",ko:"생산성"},{w:"performance",ko:"성과"},{w:"effectiveness",ko:"효과"},{w:"outcome",ko:"성과, 결과"},
{w:"impact",ko:"영향"},{w:"influence",ko:"영향력"},{w:"consequence",ko:"결과"},{w:"implication",ko:"함의, 영향"},
// 추가 빈출 어휘
{w:"vacate",ko:"비우다, 떠나다"},{w:"commute",ko:"통근(하다)"},{w:"commuter",ko:"통근자"},{w:"premise",ko:"건물(premises)"},
{w:"agenda",ko:"의제"},{w:"quota",ko:"할당량"},{w:"surcharge",ko:"추가 요금"},{w:"overdue",ko:"기한이 지난"},
{w:"outstanding",ko:"미지불의, 뛰어난"},{w:"pending",ko:"미결의, 보류 중인"},{w:"prior",ko:"이전의, 우선하는"},{w:"upcoming",ko:"곧 있을"},
{w:"forthcoming",ko:"다가오는"},{w:"imminent",ko:"임박한"},{w:"timely",ko:"시기적절한"},{w:"overnight",ko:"하룻밤의"},
{w:"longstanding",ko:"오래된"},{w:"ongoing",ko:"진행 중인"},{w:"thriving",ko:"번창하는"},{w:"booming",ko:"호황인"},
{w:"lucrative",ko:"수익성 좋은"},{w:"cost-effective",ko:"비용 효율이 높은"},{w:"economical",ko:"경제적인"},{w:"modest",ko:"적당한, 겸손한"},
{w:"moderate",ko:"적당한"},{w:"reasonable",ko:"합리적인"},{w:"competent",ko:"유능한"},{w:"diligent",ko:"근면한"},
{w:"dedicated",ko:"헌신적인"},{w:"committed",ko:"헌신하는"},{w:"enthusiastic",ko:"열정적인"},{w:"ambitious",ko:"야심 찬"},
{w:"innovative",ko:"혁신적인"},{w:"creative",ko:"창의적인"},{w:"resourceful",ko:"수완이 좋은"},{w:"versatile",ko:"다재다능한"},
{w:"meticulous",ko:"꼼꼼한"},{w:"prudent",ko:"신중한"},{w:"cautious",ko:"조심스러운"},{w:"courteous",ko:"예의 바른"},
{w:"hospitable",ko:"환대하는"},{w:"cordial",ko:"화기애애한"},{w:"prestigious",ko:"명망 있는"},{w:"renowned",ko:"유명한"},
{w:"distinguished",ko:"저명한"},{w:"exceptional",ko:"뛰어난"},{w:"outstanding",ko:"우수한"},{w:"superior",ko:"우수한, 상급의"},
{w:"inferior",ko:"열등한"},{w:"intermediate",ko:"중급의"},{w:"advanced",ko:"고급의, 발전된"},{w:"sophisticated",ko:"정교한"},
{w:"state-of-the-art",ko:"최첨단의"},{w:"cutting-edge",ko:"최첨단의"},{w:"obsolete",ko:"구식의"},{w:"outdated",ko:"구식의"},
{w:"redundant",ko:"불필요한, 잉여의"},{w:"surplus",ko:"잉여의"},{w:"scarce",ko:"부족한"},{w:"abundant",ko:"풍부한"},
{w:"ample",ko:"충분한"},{w:"plentiful",ko:"풍부한"},{w:"minimal",ko:"최소의"},{w:"marginal",ko:"미미한, 한계의"},
{w:"steady",ko:"꾸준한"},{w:"gradual",ko:"점진적인"},{w:"rapid",ko:"빠른"},{w:"drastic",ko:"급격한"},
{w:"dramatic",ko:"극적인"},{w:"remarkable",ko:"놀랄 만한"},{w:"noticeable",ko:"눈에 띄는"},{w:"evident",ko:"명백한"},
{w:"apparent",ko:"분명한"},{w:"obvious",ko:"명백한"},{w:"explicit",ko:"명백한"},{w:"implicit",ko:"암시적인"},
{w:"ambiguous",ko:"모호한"},{w:"vague",ko:"모호한"},{w:"controversial",ko:"논란이 많은"},{w:"confidential",ko:"기밀의"},
{w:"discreet",ko:"신중한"},{w:"reluctant",ko:"꺼리는"},{w:"willing",ko:"기꺼이 하는"},{w:"eager",ko:"열망하는"},
{w:"keen",ko:"열망하는, 예리한"},{w:"capable",ko:"할 수 있는"},{w:"incapable",ko:"할 수 없는"},{w:"liable",ko:"~하기 쉬운"},
{w:"prone",ko:"~하기 쉬운"},{w:"inclined",ko:"~하는 경향이 있는"},{w:"subject to",ko:"~의 대상인"},{w:"exempt",ko:"면제된"}
];
