// 회화 표현 & 대화 — window.PHRASES / window.DIALOGS / window.SCENES / window.LEVELS
// lv: 1=기초, 2=중급, 3=고급
window.SCENES = {
  greet:"인사·소개", small:"일상 잡담", food:"식당·카페", shop:"쇼핑",
  travel:"여행·공항·호텔", direction:"길찾기·교통", phone:"전화·약속",
  work:"직장·비즈니스", react:"감정·리액션", help:"문제·도움"
};
window.LEVELS = { 1:"기초", 2:"중급", 3:"고급" };

window.PHRASES = [
// ===== 기초 회화 (lv1) — 짧고 꼭 쓰는 필수 표현 =====
{en:"Nice to meet you.", ko:"만나서 반가워요.", scene:"greet", lv:1},
{en:"Long time no see!", ko:"오랜만이에요!", scene:"greet", lv:1},
{en:"How are you doing?", ko:"잘 지내요?", scene:"greet", lv:1},
{en:"Where are you from?", ko:"어디서 오셨어요?", scene:"greet", lv:1},
{en:"How was your day?", ko:"오늘 하루 어땠어요?", scene:"greet", lv:1},
{en:"See you later.", ko:"나중에 봐요.", scene:"greet", lv:1},
{en:"Take care!", ko:"잘 지내요!", scene:"greet", lv:1},
{en:"Have a good one.", ko:"좋은 하루 보내세요.", scene:"greet", lv:1},
{en:"Thank you so much.", ko:"정말 고마워요.", scene:"greet", lv:1},
{en:"I'm sorry.", ko:"죄송해요.", scene:"greet", lv:1},
{en:"Excuse me.", ko:"실례합니다.", scene:"greet", lv:1},
{en:"No problem.", ko:"괜찮아요. / 천만에요.", scene:"greet", lv:1},
{en:"How's it going?", ko:"잘 지내요?", scene:"small", lv:1},
{en:"That sounds fun.", ko:"재밌겠네요.", scene:"small", lv:1},
{en:"Did you sleep well?", ko:"잘 잤어요?", scene:"small", lv:1},
{en:"You look great today.", ko:"오늘 멋져 보여요.", scene:"small", lv:1},
{en:"The weather is nice today.", ko:"오늘 날씨가 좋네요.", scene:"small", lv:1},
{en:"No way, really?", ko:"설마, 진짜요?", scene:"small", lv:1},
{en:"A table for two, please.", ko:"두 명 자리 부탁해요.", scene:"food", lv:1},
{en:"Could I see the menu, please?", ko:"메뉴 좀 볼 수 있을까요?", scene:"food", lv:1},
{en:"Can I get this to go?", ko:"이거 포장돼요?", scene:"food", lv:1},
{en:"Could I have some water?", ko:"물 좀 주시겠어요?", scene:"food", lv:1},
{en:"Are you ready to order?", ko:"주문하시겠어요?", scene:"food", lv:1},
{en:"Can I have one more, please?", ko:"하나 더 주시겠어요?", scene:"food", lv:1},
{en:"Everything was delicious.", ko:"다 맛있었어요.", scene:"food", lv:1},
{en:"How much is this?", ko:"이거 얼마예요?", scene:"shop", lv:1},
{en:"Can I try this on?", ko:"이거 입어 봐도 돼요?", scene:"shop", lv:1},
{en:"Where is the fitting room?", ko:"탈의실이 어디예요?", scene:"shop", lv:1},
{en:"Do you take credit cards?", ko:"카드 받으세요?", scene:"shop", lv:1},
{en:"I'll take it.", ko:"이걸로 할게요.", scene:"shop", lv:1},
{en:"Can I have the receipt?", ko:"영수증 주시겠어요?", scene:"shop", lv:1},
{en:"Where can I pay?", ko:"어디서 계산해요?", scene:"shop", lv:1},
{en:"It doesn't fit me.", ko:"저한테 안 맞아요.", scene:"shop", lv:1},
{en:"I'd like to check in, please.", ko:"체크인하고 싶어요.", scene:"travel", lv:1},
{en:"What time is checkout?", ko:"체크아웃 몇 시예요?", scene:"travel", lv:1},
{en:"Is breakfast included?", ko:"조식 포함인가요?", scene:"travel", lv:1},
{en:"I'd like a window seat.", ko:"창가 자리로 주세요.", scene:"travel", lv:1},
{en:"Where can I get a taxi?", ko:"택시는 어디서 타요?", scene:"travel", lv:1},
{en:"What's the Wi-Fi password?", ko:"와이파이 비밀번호가 뭐예요?", scene:"travel", lv:1},
{en:"Where is the restroom?", ko:"화장실이 어디예요?", scene:"travel", lv:1},
{en:"Is it far from here?", ko:"여기서 멀어요?", scene:"direction", lv:1},
{en:"Go straight and turn left.", ko:"쭉 가서 왼쪽으로 도세요.", scene:"direction", lv:1},
{en:"How long does it take?", ko:"얼마나 걸려요?", scene:"direction", lv:1},
{en:"I think I'm lost.", ko:"길을 잃은 것 같아요.", scene:"direction", lv:1},
{en:"What's the fare?", ko:"요금이 얼마예요?", scene:"direction", lv:1},
{en:"Who's calling, please?", ko:"누구세요? (전화 거신 분)", scene:"phone", lv:1},
{en:"Can I leave a message?", ko:"메시지 남길 수 있을까요?", scene:"phone", lv:1},
{en:"I'll call you back later.", ko:"나중에 다시 전화할게요.", scene:"phone", lv:1},
{en:"Are you free this Friday?", ko:"이번 주 금요일에 시간 돼요?", scene:"phone", lv:1},
{en:"Sorry, I'm running late.", ko:"죄송해요, 좀 늦을 것 같아요.", scene:"phone", lv:1},
{en:"Could you send me the file?", ko:"그 파일 좀 보내 주시겠어요?", scene:"work", lv:1},
{en:"What's the deadline?", ko:"마감이 언제예요?", scene:"work", lv:1},
{en:"Good job, everyone.", ko:"모두 수고하셨어요.", scene:"work", lv:1},
{en:"I appreciate your help.", ko:"도와주셔서 감사해요.", scene:"work", lv:1},
{en:"That's awesome!", ko:"정말 멋지다!", scene:"react", lv:1},
{en:"I can't believe it.", ko:"믿을 수가 없어요.", scene:"react", lv:1},
{en:"Don't worry about it.", ko:"신경 쓰지 마세요.", scene:"react", lv:1},
{en:"It's not a big deal.", ko:"별일 아니에요.", scene:"react", lv:1},
{en:"Cheer up!", ko:"기운 내요!", scene:"react", lv:1},
{en:"Good for you!", ko:"잘됐네요!", scene:"react", lv:1},
{en:"That's too bad.", ko:"안됐네요.", scene:"react", lv:1},
{en:"Could you help me out?", ko:"좀 도와주시겠어요?", scene:"help", lv:1},
{en:"Can you fix it?", ko:"고쳐 주실 수 있어요?", scene:"help", lv:1},
{en:"Could you speak more slowly?", ko:"좀 더 천천히 말씀해 주시겠어요?", scene:"help", lv:1},
{en:"What does this word mean?", ko:"이 단어 무슨 뜻이에요?", scene:"help", lv:1},
{en:"How do you spell that?", ko:"그거 철자가 어떻게 돼요?", scene:"help", lv:1},
{en:"I need to see a doctor.", ko:"병원에 가야 할 것 같아요.", scene:"help", lv:1},
{en:"Call the police, please.", ko:"경찰 좀 불러 주세요.", scene:"help", lv:1},

// ===== 중급 회화 (lv2) — 상황별 정중한 표현·잡담 =====
{en:"How have you been?", ko:"그동안 어떻게 지냈어요?", scene:"greet", lv:2},
{en:"It's nice to finally meet you.", ko:"드디어 만나서 반가워요.", scene:"greet", lv:2},
{en:"I've heard a lot about you.", ko:"말씀 많이 들었어요.", scene:"greet", lv:2},
{en:"What do you do for a living?", ko:"무슨 일 하세요?", scene:"greet", lv:2},
{en:"How do you two know each other?", ko:"두 분은 어떻게 아는 사이예요?", scene:"greet", lv:2},
{en:"Let me introduce myself.", ko:"제 소개를 할게요.", scene:"greet", lv:2},
{en:"It was great talking to you.", ko:"얘기 즐거웠어요.", scene:"greet", lv:2},
{en:"Let's keep in touch.", ko:"연락하고 지내요.", scene:"greet", lv:2},
{en:"What brings you here?", ko:"여긴 어쩐 일이세요?", scene:"greet", lv:2},
{en:"Say hi to your family for me.", ko:"가족분들께 안부 전해 주세요.", scene:"greet", lv:2},
{en:"I'm looking forward to working with you.", ko:"함께 일하게 되어 기대돼요.", scene:"greet", lv:2},
{en:"I should get going.", ko:"이만 가 봐야겠어요.", scene:"greet", lv:2},
{en:"What are you up to this weekend?", ko:"이번 주말에 뭐 해요?", scene:"small", lv:2},
{en:"Nothing much, just relaxing.", ko:"별거 없어요, 그냥 쉬어요.", scene:"small", lv:2},
{en:"I can't complain.", ko:"그럭저럭 잘 지내요.", scene:"small", lv:2},
{en:"What's new with you?", ko:"요즘 별일 없어요?", scene:"small", lv:2},
{en:"Time flies.", ko:"시간 참 빠르네요.", scene:"small", lv:2},
{en:"What do you do in your free time?", ko:"여가 시간엔 뭐 하세요?", scene:"small", lv:2},
{en:"Let's grab a coffee sometime.", ko:"언제 커피 한잔해요.", scene:"small", lv:2},
{en:"How's your family doing?", ko:"가족분들은 잘 지내세요?", scene:"small", lv:2},
{en:"That makes sense.", ko:"그럴 만하네요.", scene:"small", lv:2},
{en:"What do you recommend?", ko:"뭐가 맛있어요? (추천 좀요)", scene:"food", lv:2},
{en:"I'll have the same.", ko:"저도 같은 걸로 할게요.", scene:"food", lv:2},
{en:"Could we get the check, please?", ko:"계산서 좀 주시겠어요?", scene:"food", lv:2},
{en:"Is this dish spicy?", ko:"이 음식 매워요?", scene:"food", lv:2},
{en:"I'm allergic to peanuts.", ko:"저 땅콩 알레르기가 있어요.", scene:"food", lv:2},
{en:"Can we split the bill?", ko:"따로 계산할 수 있어요?", scene:"food", lv:2},
{en:"It's on me.", ko:"제가 살게요.", scene:"food", lv:2},
{en:"How would you like your steak?", ko:"스테이크 어떻게 익혀 드릴까요?", scene:"food", lv:2},
{en:"Could I get a refill?", ko:"리필 좀 해 주시겠어요?", scene:"food", lv:2},
{en:"I'd like to make a reservation.", ko:"예약하고 싶은데요.", scene:"food", lv:2},
{en:"Do you have a vegetarian option?", ko:"채식 메뉴 있나요?", scene:"food", lv:2},
{en:"I'm just looking, thanks.", ko:"그냥 구경 중이에요, 감사해요.", scene:"shop", lv:2},
{en:"Do you have this in a smaller size?", ko:"이거 더 작은 사이즈 있어요?", scene:"shop", lv:2},
{en:"Is this on sale?", ko:"이거 할인하는 거예요?", scene:"shop", lv:2},
{en:"Can I get a refund?", ko:"환불 받을 수 있어요?", scene:"shop", lv:2},
{en:"I'd like to exchange this.", ko:"이거 교환하고 싶어요.", scene:"shop", lv:2},
{en:"Do you have this in another color?", ko:"다른 색깔도 있어요?", scene:"shop", lv:2},
{en:"That's a bit too expensive.", ko:"좀 비싸네요.", scene:"shop", lv:2},
{en:"Do you offer gift wrapping?", ko:"선물 포장돼요?", scene:"shop", lv:2},
{en:"I'm looking for a gift for my mom.", ko:"엄마 선물을 찾고 있어요.", scene:"shop", lv:2},
{en:"Can you hold this for me?", ko:"이거 좀 맡아 주실 수 있어요?", scene:"shop", lv:2},
{en:"Do you have any rooms available?", ko:"빈 방 있어요?", scene:"travel", lv:2},
{en:"Where is the boarding gate?", ko:"탑승구가 어디예요?", scene:"travel", lv:2},
{en:"My flight got delayed.", ko:"제 항공편이 지연됐어요.", scene:"travel", lv:2},
{en:"How do I get to downtown?", ko:"시내까지 어떻게 가요?", scene:"travel", lv:2},
{en:"I lost my luggage.", ko:"짐을 잃어버렸어요.", scene:"travel", lv:2},
{en:"Is there a tour available?", ko:"투어 프로그램 있나요?", scene:"travel", lv:2},
{en:"I have a reservation under Kim.", ko:"김으로 예약했는데요.", scene:"travel", lv:2},
{en:"Is it within walking distance?", ko:"걸어갈 만한 거리예요?", scene:"travel", lv:2},
{en:"Can I store my bags here?", ko:"여기 짐 좀 맡길 수 있어요?", scene:"travel", lv:2},
{en:"Could you take a picture for us?", ko:"저희 사진 좀 찍어 주시겠어요?", scene:"travel", lv:2},
{en:"Excuse me, how do I get to the station?", ko:"실례지만, 역에 어떻게 가요?", scene:"direction", lv:2},
{en:"It's right around the corner.", ko:"바로 저 모퉁이에 있어요.", scene:"direction", lv:2},
{en:"Which bus goes to the airport?", ko:"공항 가는 버스가 어떤 거예요?", scene:"direction", lv:2},
{en:"Where is the nearest subway station?", ko:"가장 가까운 지하철역이 어디예요?", scene:"direction", lv:2},
{en:"Do I need to transfer?", ko:"환승해야 하나요?", scene:"direction", lv:2},
{en:"Could you show me on the map?", ko:"지도에서 좀 보여 주시겠어요?", scene:"direction", lv:2},
{en:"Does this train stop at City Hall?", ko:"이 기차 시청역에 서요?", scene:"direction", lv:2},
{en:"It's two stops from here.", ko:"여기서 두 정거장이에요.", scene:"direction", lv:2},
{en:"May I speak to Mr. Lee?", ko:"이 선생님과 통화할 수 있을까요?", scene:"phone", lv:2},
{en:"Could you hold on a second?", ko:"잠시만 기다려 주시겠어요?", scene:"phone", lv:2},
{en:"You've got the wrong number.", ko:"전화 잘못 거셨어요.", scene:"phone", lv:2},
{en:"Let's set up a meeting.", ko:"미팅을 잡아요.", scene:"phone", lv:2},
{en:"Does 3 p.m. work for you?", ko:"오후 3시 괜찮으세요?", scene:"phone", lv:2},
{en:"Can we reschedule?", ko:"일정을 다시 잡을 수 있을까요?", scene:"phone", lv:2},
{en:"Something came up.", ko:"갑자기 일이 생겼어요.", scene:"phone", lv:2},
{en:"Let me check my schedule.", ko:"일정 좀 확인해 볼게요.", scene:"phone", lv:2},
{en:"Can we go over this together?", ko:"이거 같이 한번 볼까요?", scene:"work", lv:2},
{en:"I'll take care of it.", ko:"제가 처리할게요.", scene:"work", lv:2},
{en:"I'm a bit behind schedule.", ko:"일정이 좀 밀렸어요.", scene:"work", lv:2},
{en:"That works for me.", ko:"저는 괜찮아요. (그렇게 하죠)", scene:"work", lv:2},
{en:"Can you cover for me?", ko:"제 일 좀 대신 봐 주실 수 있어요?", scene:"work", lv:2},
{en:"Let's split the work.", ko:"일을 나눠서 하죠.", scene:"work", lv:2},
{en:"You must be kidding.", ko:"농담이죠. (말도 안 돼요)", scene:"react", lv:2},
{en:"I'm so proud of you.", ko:"네가 정말 자랑스러워.", scene:"react", lv:2},
{en:"That's a relief.", ko:"다행이네요.", scene:"react", lv:2},
{en:"What a shame.", ko:"아쉽네요. / 안타깝네요.", scene:"react", lv:2},
{en:"I feel the same way.", ko:"저도 같은 마음이에요.", scene:"react", lv:2},
{en:"I'm thrilled to hear that.", ko:"그 소식 들으니 정말 기뻐요.", scene:"react", lv:2},
{en:"I have a problem with my order.", ko:"주문에 문제가 있어요.", scene:"help", lv:2},
{en:"Something is wrong with this.", ko:"이거 뭔가 이상해요.", scene:"help", lv:2},
{en:"I don't understand. Could you say that again?", ko:"이해가 안 돼요. 다시 말씀해 주시겠어요?", scene:"help", lv:2},
{en:"Excuse me, can I ask you something?", ko:"실례지만 뭐 좀 여쭤봐도 될까요?", scene:"help", lv:2},
{en:"Could you write it down for me?", ko:"좀 적어 주시겠어요?", scene:"help", lv:2},
{en:"Is there anyone who speaks Korean?", ko:"한국어 하시는 분 있나요?", scene:"help", lv:2},
{en:"Can I get a hand with this?", ko:"이것 좀 도와주실래요?", scene:"help", lv:2},

// ===== 고급 회화 (lv3) — 관용·비즈니스·뉘앙스 표현 =====
{en:"Let's play it by ear.", ko:"상황 봐서 정하죠.", scene:"small", lv:3},
{en:"I'll take a rain check.", ko:"다음 기회로 미룰게요.", scene:"small", lv:3},
{en:"It's a long story.", ko:"말하자면 길어요.", scene:"small", lv:3},
{en:"It's been one of those days.", ko:"오늘 좀 그런 날이에요.", scene:"small", lv:3},
{en:"I'm really into hiking these days.", ko:"요즘 등산에 푹 빠졌어요.", scene:"small", lv:3},
{en:"That's not my cup of tea.", ko:"제 취향은 아니에요.", scene:"small", lv:3},
{en:"Let's hit the road.", ko:"이제 출발하죠.", scene:"small", lv:3},
{en:"I'm swamped with work.", ko:"일이 산더미예요.", scene:"small", lv:3},
{en:"That rings a bell.", ko:"어디서 들어본 것 같아요.", scene:"small", lv:3},
{en:"Let's keep it between us.", ko:"우리끼리 비밀로 해요.", scene:"small", lv:3},
{en:"Let's get the ball rolling.", ko:"이제 시작해 봅시다.", scene:"work", lv:3},
{en:"Let me get back to you on that.", ko:"그건 다시 알려 드릴게요.", scene:"work", lv:3},
{en:"Let's touch base next week.", ko:"다음 주에 다시 얘기해요.", scene:"work", lv:3},
{en:"Could you clarify what you mean?", ko:"무슨 뜻인지 좀 더 설명해 주시겠어요?", scene:"work", lv:3},
{en:"Let's wrap this up.", ko:"이쯤에서 마무리하죠.", scene:"work", lv:3},
{en:"I'll keep you posted.", ko:"진행 상황 계속 알려 드릴게요.", scene:"work", lv:3},
{en:"Can I pick your brain for a second?", ko:"잠깐 조언 좀 구해도 될까요?", scene:"work", lv:3},
{en:"Let's circle back to this later.", ko:"이건 나중에 다시 다루죠.", scene:"work", lv:3},
{en:"Let's cut to the chase.", ko:"본론으로 들어가죠.", scene:"work", lv:3},
{en:"We're on the same page.", ko:"우리 생각이 같네요.", scene:"work", lv:3},
{en:"Could you walk me through it?", ko:"차근차근 설명해 주시겠어요?", scene:"work", lv:3},
{en:"I'd appreciate it if you could help.", ko:"도와주시면 감사하겠습니다.", scene:"work", lv:3},
{en:"Let's iron out the details.", ko:"세부 사항을 조율해 보죠.", scene:"work", lv:3},
{en:"Let me sleep on it.", ko:"좀 더 생각해 볼게요.", scene:"work", lv:3},
{en:"That's a tough call.", ko:"결정하기 어렵네요.", scene:"work", lv:3},
{en:"Let's not jump to conclusions.", ko:"성급히 결론 내리지 맙시다.", scene:"work", lv:3},
{en:"It slipped my mind.", ko:"깜빡했어요.", scene:"work", lv:3},
{en:"I'll keep that in mind.", ko:"명심할게요.", scene:"react", lv:3},
{en:"That's easier said than done.", ko:"말처럼 쉽지 않아요.", scene:"react", lv:3},
{en:"I couldn't agree more.", ko:"전적으로 동의해요.", scene:"react", lv:3},
{en:"Don't take it personally.", ko:"기분 나쁘게 받아들이지 마세요.", scene:"react", lv:3},
{en:"You can say that again.", ko:"정말 그래요. (맞는 말이에요)", scene:"react", lv:3},
{en:"That drives me crazy.", ko:"그것 때문에 미치겠어요.", scene:"react", lv:3},
{en:"Let's not get ahead of ourselves.", ko:"너무 앞서가지 맙시다.", scene:"react", lv:3},
{en:"I'm on the fence about it.", ko:"결정을 못 내리겠어요.", scene:"react", lv:3},
{en:"It's up to you.", ko:"당신에게 달렸어요.", scene:"react", lv:3},
{en:"Let's give it a shot.", ko:"한번 해 봅시다.", scene:"react", lv:3},
{en:"I'll get the hang of it.", ko:"곧 익숙해질 거예요.", scene:"react", lv:3},
{en:"Let's make the most of it.", ko:"최대한 활용해 봅시다.", scene:"react", lv:3},
{en:"I'm all ears.", ko:"잘 듣고 있어요. (어서 말해 보세요)", scene:"help", lv:3},
{en:"Bear with me for a moment.", ko:"잠시만 기다려 주세요.", scene:"help", lv:3},
{en:"I'm not sure I follow.", ko:"잘 이해가 안 가요.", scene:"help", lv:3}
];

// 대화 완성: a(상대의 말)에 알맞은 응답 b 고르기  (lv: 난이도)
window.DIALOGS = [
{a:"Nice to meet you.", b:"Nice to meet you too.", ko:"만나서 반가워요. → 저도 반가워요.", scene:"greet", lv:1},
{a:"Thank you for your help.", b:"No problem, anytime.", ko:"도와줘서 고마워요. → 별말씀을요, 언제든지요.", scene:"react", lv:1},
{a:"How are you today?", b:"Pretty good, thanks. And you?", ko:"오늘 어때요? → 좋아요, 고마워요. 당신은요?", scene:"greet", lv:1},
{a:"Could you pass me the salt?", b:"Sure, here you go.", ko:"소금 좀 건네줄래요? → 네, 여기요.", scene:"food", lv:1},
{a:"See you tomorrow!", b:"See you. Have a good night.", ko:"내일 봐요! → 또 봐요. 좋은 밤 보내세요.", scene:"greet", lv:1},
{a:"Are you ready to order?", b:"Yes, I'll have the chicken salad.", ko:"주문하시겠어요? → 네, 치킨 샐러드 주세요.", scene:"food", lv:1},
{a:"How much is this?", b:"It's fifteen dollars.", ko:"이거 얼마예요? → 15달러예요.", scene:"shop", lv:1},
{a:"Happy birthday!", b:"Thank you so much!", ko:"생일 축하해요! → 정말 고마워요!", scene:"react", lv:1},
{a:"Can I help you find anything?", b:"I'm just looking, thanks.", ko:"찾으시는 거 도와드릴까요? → 그냥 구경 중이에요, 고마워요.", scene:"shop", lv:1},
{a:"Excuse me, is this seat taken?", b:"No, it's free.", ko:"실례지만 이 자리 주인 있어요? → 아니요, 비어 있어요.", scene:"travel", lv:1},
{a:"Would you like anything to drink?", b:"Just water, thanks.", ko:"마실 것 드릴까요? → 그냥 물이면 돼요, 고마워요.", scene:"food", lv:1},
{a:"What's wrong?", b:"I think I lost my wallet.", ko:"무슨 일이에요? → 지갑을 잃어버린 것 같아요.", scene:"help", lv:1},
{a:"How was your weekend?", b:"It was great. I went hiking.", ko:"주말 어땠어요? → 좋았어요, 등산 갔어요.", scene:"small", lv:2},
{a:"How about grabbing lunch?", b:"Sure, where do you want to go?", ko:"점심 먹을래요? → 좋아요, 어디로 갈까요?", scene:"food", lv:2},
{a:"I'm sorry I'm late.", b:"That's okay, don't worry about it.", ko:"늦어서 미안해요. → 괜찮아요, 신경 쓰지 마세요.", scene:"react", lv:2},
{a:"Do you mind if I sit here?", b:"Not at all, go ahead.", ko:"여기 앉아도 될까요? → 그럼요, 앉으세요.", scene:"small", lv:2},
{a:"What time should we meet?", b:"How about 7 o'clock?", ko:"몇 시에 만날까요? → 7시 어때요?", scene:"phone", lv:2},
{a:"How would you like your coffee?", b:"With milk and no sugar, please.", ko:"커피 어떻게 드릴까요? → 우유 넣고 설탕은 빼 주세요.", scene:"food", lv:2},
{a:"Can I call you back later?", b:"Sure, talk to you then.", ko:"이따 다시 전화해도 돼요? → 네, 그때 얘기해요.", scene:"phone", lv:2},
{a:"How do I get to the museum?", b:"Go straight and turn right.", ko:"박물관에 어떻게 가요? → 쭉 가서 오른쪽으로 도세요.", scene:"direction", lv:2},
{a:"This is too expensive for me.", b:"I can give you a small discount.", ko:"저한테는 너무 비싸요. → 조금 깎아 드릴 수 있어요.", scene:"shop", lv:2},
{a:"Could you speak more slowly?", b:"Of course. Is this better?", ko:"좀 천천히 말해 주시겠어요? → 그럼요. 이게 더 나아요?", scene:"help", lv:2},
{a:"What do you do for a living?", b:"I work as a nurse.", ko:"무슨 일 하세요? → 간호사로 일해요.", scene:"greet", lv:2},
{a:"Do you have this in a larger size?", b:"Let me check for you.", ko:"이거 더 큰 사이즈 있어요? → 확인해 드릴게요.", scene:"shop", lv:2},
{a:"I don't feel well today.", b:"You should get some rest.", ko:"오늘 몸이 안 좋아요. → 좀 쉬는 게 좋겠어요.", scene:"help", lv:2},
{a:"Can we reschedule our meeting?", b:"Sure, what day works for you?", ko:"미팅 일정 바꿀 수 있을까요? → 그럼요, 어느 날이 좋으세요?", scene:"phone", lv:2},
{a:"How long does it take to get there?", b:"About twenty minutes by bus.", ko:"거기까지 얼마나 걸려요? → 버스로 20분쯤요.", scene:"direction", lv:2},
{a:"Would you like to join us?", b:"I'd love to, thanks.", ko:"같이 하실래요? → 좋아요, 고마워요.", scene:"small", lv:2},
{a:"Can I get the check, please?", b:"Sure, I'll bring it right away.", ko:"계산서 좀 주시겠어요? → 네, 바로 가져다드릴게요.", scene:"food", lv:2},
{a:"It was nice meeting you.", b:"Likewise. Let's keep in touch.", ko:"만나서 반가웠어요. → 저도요. 연락하고 지내요.", scene:"greet", lv:2},
{a:"Do you need a hand?", b:"Yes, please. That would be great.", ko:"도와줄까요? → 네, 부탁해요. 그럼 정말 좋죠.", scene:"help", lv:2},
{a:"Could you take a picture for us?", b:"Sure, say cheese!", ko:"사진 좀 찍어 주시겠어요? → 그럼요, 김치!", scene:"travel", lv:2},
{a:"Is breakfast included?", b:"Yes, it's served until ten.", ko:"조식 포함인가요? → 네, 10시까지 제공돼요.", scene:"travel", lv:2},
{a:"How's your new job?", b:"It's challenging but fun.", ko:"새 직장 어때요? → 힘들지만 재밌어요.", scene:"work", lv:2},
{a:"Sorry, I didn't catch your name.", b:"It's Daniel. Nice to meet you.", ko:"죄송해요, 이름을 못 들었어요. → 대니얼이에요. 반가워요.", scene:"greet", lv:2},
{a:"Would you like to leave a message?", b:"Yes, please tell him I called.", ko:"메시지 남기시겠어요? → 네, 제가 전화했다고 전해 주세요.", scene:"phone", lv:2},
{a:"Can I try this on?", b:"Of course, the fitting room is over there.", ko:"이거 입어 봐도 돼요? → 그럼요, 탈의실은 저쪽이에요.", scene:"shop", lv:2},
{a:"Let's call it a day.", b:"Sounds good. See you tomorrow.", ko:"오늘은 이만하죠. → 좋아요. 내일 봐요.", scene:"work", lv:3},
{a:"Shall we get the ball rolling?", b:"Yes, let's dive right in.", ko:"이제 시작할까요? → 네, 바로 시작하죠.", scene:"work", lv:3},
{a:"Can I pick your brain for a minute?", b:"Of course, what's on your mind?", ko:"잠깐 조언 좀 구해도 될까요? → 그럼요, 무슨 일인데요?", scene:"work", lv:3},
{a:"Let's cut to the chase.", b:"Agreed. What's the bottom line?", ko:"본론으로 들어가죠. → 좋아요. 결론이 뭐죠?", scene:"work", lv:3},
{a:"I'm on the fence about it.", b:"Take your time, no rush.", ko:"결정을 못 내리겠어요. → 천천히 하세요, 급할 거 없어요.", scene:"react", lv:3}
];
