// 기초 회화 단어 (일상 생활) — window.BASIC
window.BASIC = [
// 사람·가족·관계
{w:"family",ko:"가족"},{w:"parents",ko:"부모"},{w:"father",ko:"아버지"},{w:"mother",ko:"어머니"},
{w:"son",ko:"아들"},{w:"daughter",ko:"딸"},{w:"brother",ko:"형제"},{w:"sister",ko:"자매"},
{w:"husband",ko:"남편"},{w:"wife",ko:"아내"},{w:"child",ko:"아이"},{w:"baby",ko:"아기"},
{w:"grandfather",ko:"할아버지"},{w:"grandmother",ko:"할머니"},{w:"uncle",ko:"삼촌"},{w:"aunt",ko:"이모, 고모"},
{w:"cousin",ko:"사촌"},{w:"nephew",ko:"조카(남)"},{w:"niece",ko:"조카(여)"},{w:"relative",ko:"친척"},
{w:"friend",ko:"친구"},{w:"neighbor",ko:"이웃"},{w:"stranger",ko:"낯선 사람"},{w:"guest",ko:"손님"},
{w:"couple",ko:"부부, 커플"},{w:"adult",ko:"성인"},{w:"teenager",ko:"십대"},{w:"kid",ko:"아이"},
{w:"man",ko:"남자"},{w:"woman",ko:"여자"},{w:"boy",ko:"소년"},{w:"girl",ko:"소녀"},
{w:"people",ko:"사람들"},{w:"person",ko:"사람"},{w:"name",ko:"이름"},{w:"age",ko:"나이"},
// 몸·건강
{w:"body",ko:"몸"},{w:"head",ko:"머리"},{w:"hair",ko:"머리카락"},{w:"face",ko:"얼굴"},
{w:"eye",ko:"눈"},{w:"ear",ko:"귀"},{w:"nose",ko:"코"},{w:"mouth",ko:"입"},
{w:"tooth",ko:"이, 치아"},{w:"tongue",ko:"혀"},{w:"neck",ko:"목"},{w:"shoulder",ko:"어깨"},
{w:"arm",ko:"팔"},{w:"hand",ko:"손"},{w:"finger",ko:"손가락"},{w:"leg",ko:"다리"},
{w:"foot",ko:"발"},{w:"knee",ko:"무릎"},{w:"back",ko:"등, 허리"},{w:"chest",ko:"가슴"},
{w:"stomach",ko:"배, 위"},{w:"skin",ko:"피부"},{w:"bone",ko:"뼈"},{w:"heart",ko:"심장"},
{w:"blood",ko:"피"},{w:"brain",ko:"뇌"},{w:"health",ko:"건강"},{w:"sick",ko:"아픈"},
{w:"ill",ko:"병든"},{w:"pain",ko:"통증"},{w:"fever",ko:"열"},{w:"cough",ko:"기침"},
{w:"cold",ko:"감기"},{w:"headache",ko:"두통"},{w:"medicine",ko:"약"},{w:"doctor",ko:"의사"},
{w:"nurse",ko:"간호사"},{w:"hospital",ko:"병원"},{w:"dentist",ko:"치과의사"},{w:"injury",ko:"부상"},
{w:"wound",ko:"상처"},{w:"healthy",ko:"건강한"},{w:"tired",ko:"피곤한"},{w:"sleepy",ko:"졸린"},
// 음식·요리
{w:"food",ko:"음식"},{w:"meal",ko:"식사"},{w:"breakfast",ko:"아침 식사"},{w:"lunch",ko:"점심"},
{w:"dinner",ko:"저녁 식사"},{w:"snack",ko:"간식"},{w:"rice",ko:"쌀, 밥"},{w:"bread",ko:"빵"},
{w:"noodle",ko:"국수"},{w:"soup",ko:"수프, 국"},{w:"meat",ko:"고기"},{w:"beef",ko:"소고기"},
{w:"pork",ko:"돼지고기"},{w:"chicken",ko:"닭고기"},{w:"fish",ko:"생선"},{w:"egg",ko:"달걀"},
{w:"vegetable",ko:"채소"},{w:"fruit",ko:"과일"},{w:"apple",ko:"사과"},{w:"banana",ko:"바나나"},
{w:"orange",ko:"오렌지"},{w:"grape",ko:"포도"},{w:"strawberry",ko:"딸기"},{w:"watermelon",ko:"수박"},
{w:"tomato",ko:"토마토"},{w:"potato",ko:"감자"},{w:"onion",ko:"양파"},{w:"carrot",ko:"당근"},
{w:"garlic",ko:"마늘"},{w:"pepper",ko:"후추, 고추"},{w:"salt",ko:"소금"},{w:"sugar",ko:"설탕"},
{w:"oil",ko:"기름"},{w:"butter",ko:"버터"},{w:"cheese",ko:"치즈"},{w:"milk",ko:"우유"},
{w:"water",ko:"물"},{w:"juice",ko:"주스"},{w:"coffee",ko:"커피"},{w:"tea",ko:"차"},
{w:"sauce",ko:"소스"},{w:"dish",ko:"요리, 접시"},{w:"recipe",ko:"조리법"},{w:"taste",ko:"맛"},
{w:"sweet",ko:"단"},{w:"sour",ko:"신"},{w:"salty",ko:"짠"},{w:"spicy",ko:"매운"},
{w:"bitter",ko:"쓴"},{w:"delicious",ko:"맛있는"},{w:"fresh",ko:"신선한"},{w:"hungry",ko:"배고픈"},
{w:"thirsty",ko:"목마른"},{w:"cook",ko:"요리하다"},{w:"bake",ko:"굽다"},{w:"boil",ko:"끓이다"},
{w:"fry",ko:"튀기다, 부치다"},{w:"cut",ko:"자르다"},{w:"mix",ko:"섞다"},{w:"eat",ko:"먹다"},
{w:"drink",ko:"마시다"},{w:"chew",ko:"씹다"},{w:"swallow",ko:"삼키다"},{w:"serve",ko:"제공하다"},
// 집·생활용품
{w:"house",ko:"집"},{w:"home",ko:"집, 가정"},{w:"room",ko:"방"},{w:"kitchen",ko:"부엌"},
{w:"bedroom",ko:"침실"},{w:"bathroom",ko:"욕실"},{w:"living room",ko:"거실"},{w:"door",ko:"문"},
{w:"window",ko:"창문"},{w:"wall",ko:"벽"},{w:"floor",ko:"바닥"},{w:"ceiling",ko:"천장"},
{w:"roof",ko:"지붕"},{w:"stairs",ko:"계단"},{w:"furniture",ko:"가구"},{w:"table",ko:"탁자"},
{w:"chair",ko:"의자"},{w:"desk",ko:"책상"},{w:"bed",ko:"침대"},{w:"sofa",ko:"소파"},
{w:"closet",ko:"옷장"},{w:"drawer",ko:"서랍"},{w:"shelf",ko:"선반"},{w:"mirror",ko:"거울"},
{w:"lamp",ko:"전등"},{w:"clock",ko:"시계"},{w:"curtain",ko:"커튼"},{w:"carpet",ko:"카펫"},
{w:"pillow",ko:"베개"},{w:"blanket",ko:"담요"},{w:"towel",ko:"수건"},{w:"soap",ko:"비누"},
{w:"toothbrush",ko:"칫솔"},{w:"refrigerator",ko:"냉장고"},{w:"oven",ko:"오븐"},{w:"stove",ko:"가스레인지"},
{w:"sink",ko:"싱크대"},{w:"plate",ko:"접시"},{w:"bowl",ko:"그릇"},{w:"cup",ko:"컵"},
{w:"glass",ko:"유리잔"},{w:"spoon",ko:"숟가락"},{w:"fork",ko:"포크"},{w:"knife",ko:"칼"},
{w:"chopsticks",ko:"젓가락"},{w:"bottle",ko:"병"},{w:"key",ko:"열쇠"},{w:"trash",ko:"쓰레기"},
// 옷·외모
{w:"clothes",ko:"옷"},{w:"shirt",ko:"셔츠"},{w:"pants",ko:"바지"},{w:"jeans",ko:"청바지"},
{w:"skirt",ko:"치마"},{w:"dress",ko:"원피스"},{w:"jacket",ko:"재킷"},{w:"coat",ko:"외투"},
{w:"sweater",ko:"스웨터"},{w:"socks",ko:"양말"},{w:"shoes",ko:"신발"},{w:"boots",ko:"부츠"},
{w:"hat",ko:"모자"},{w:"cap",ko:"모자(챙)"},{w:"gloves",ko:"장갑"},{w:"scarf",ko:"목도리"},
{w:"belt",ko:"허리띠"},{w:"tie",ko:"넥타이"},{w:"glasses",ko:"안경"},{w:"ring",ko:"반지"},
{w:"watch",ko:"손목시계"},{w:"bag",ko:"가방"},{w:"wallet",ko:"지갑"},{w:"pocket",ko:"주머니"},
{w:"button",ko:"단추"},{w:"size",ko:"크기, 치수"},{w:"wear",ko:"입다"},{w:"dress up",ko:"차려입다"},
{w:"handsome",ko:"잘생긴"},{w:"pretty",ko:"예쁜"},{w:"beautiful",ko:"아름다운"},{w:"ugly",ko:"못생긴"},
{w:"tall",ko:"키 큰"},{w:"short",ko:"키 작은, 짧은"},{w:"fat",ko:"뚱뚱한"},{w:"thin",ko:"마른"},
{w:"young",ko:"젊은"},{w:"old",ko:"늙은, 오래된"},{w:"strong",ko:"강한"},{w:"weak",ko:"약한"},
// 시간·달력
{w:"time",ko:"시간"},{w:"hour",ko:"시간(단위)"},{w:"minute",ko:"분"},{w:"second",ko:"초"},
{w:"day",ko:"날, 하루"},{w:"week",ko:"주"},{w:"month",ko:"달, 월"},{w:"year",ko:"해, 년"},
{w:"today",ko:"오늘"},{w:"tomorrow",ko:"내일"},{w:"yesterday",ko:"어제"},{w:"morning",ko:"아침"},
{w:"noon",ko:"정오"},{w:"afternoon",ko:"오후"},{w:"evening",ko:"저녁"},{w:"night",ko:"밤"},
{w:"midnight",ko:"자정"},{w:"dawn",ko:"새벽"},{w:"weekend",ko:"주말"},{w:"weekday",ko:"평일"},
{w:"holiday",ko:"휴일"},{w:"vacation",ko:"휴가, 방학"},{w:"birthday",ko:"생일"},{w:"date",ko:"날짜"},
{w:"calendar",ko:"달력"},{w:"schedule",ko:"일정"},{w:"now",ko:"지금"},{w:"soon",ko:"곧"},
{w:"early",ko:"이른"},{w:"late",ko:"늦은"},{w:"always",ko:"항상"},{w:"often",ko:"자주"},
{w:"sometimes",ko:"가끔"},{w:"never",ko:"결코 ~않다"},{w:"usually",ko:"보통"},{w:"already",ko:"이미"},
{w:"Monday",ko:"월요일"},{w:"Tuesday",ko:"화요일"},{w:"Wednesday",ko:"수요일"},{w:"Thursday",ko:"목요일"},
{w:"Friday",ko:"금요일"},{w:"Saturday",ko:"토요일"},{w:"Sunday",ko:"일요일"},{w:"spring",ko:"봄"},
{w:"summer",ko:"여름"},{w:"autumn",ko:"가을"},{w:"winter",ko:"겨울"},{w:"season",ko:"계절"},
// 자연·날씨
{w:"nature",ko:"자연"},{w:"weather",ko:"날씨"},{w:"sky",ko:"하늘"},{w:"sun",ko:"태양"},
{w:"moon",ko:"달"},{w:"star",ko:"별"},{w:"cloud",ko:"구름"},{w:"rain",ko:"비"},
{w:"snow",ko:"눈"},{w:"wind",ko:"바람"},{w:"storm",ko:"폭풍"},{w:"thunder",ko:"천둥"},
{w:"lightning",ko:"번개"},{w:"fog",ko:"안개"},{w:"rainbow",ko:"무지개"},{w:"temperature",ko:"온도"},
{w:"hot",ko:"더운"},{w:"warm",ko:"따뜻한"},{w:"cool",ko:"시원한"},{w:"freezing",ko:"몹시 추운"},
{w:"wet",ko:"젖은"},{w:"dry",ko:"마른, 건조한"},{w:"sunny",ko:"화창한"},{w:"cloudy",ko:"흐린"},
{w:"rainy",ko:"비 오는"},{w:"windy",ko:"바람 부는"},{w:"mountain",ko:"산"},{w:"hill",ko:"언덕"},
{w:"river",ko:"강"},{w:"lake",ko:"호수"},{w:"sea",ko:"바다"},{w:"ocean",ko:"대양"},
{w:"beach",ko:"해변"},{w:"island",ko:"섬"},{w:"forest",ko:"숲"},{w:"tree",ko:"나무"},
{w:"flower",ko:"꽃"},{w:"grass",ko:"풀"},{w:"leaf",ko:"잎"},{w:"root",ko:"뿌리"},
{w:"seed",ko:"씨앗"},{w:"plant",ko:"식물, 심다"},{w:"stone",ko:"돌"},{w:"rock",ko:"바위"},
{w:"sand",ko:"모래"},{w:"soil",ko:"흙"},{w:"fire",ko:"불"},{w:"earth",ko:"지구, 땅"},
{w:"air",ko:"공기"},{w:"ice",ko:"얼음"},{w:"wave",ko:"파도"},{w:"field",ko:"들판"},
// 동물
{w:"animal",ko:"동물"},{w:"dog",ko:"개"},{w:"cat",ko:"고양이"},{w:"bird",ko:"새"},
{w:"cow",ko:"소"},{w:"pig",ko:"돼지"},{w:"horse",ko:"말"},{w:"sheep",ko:"양"},
{w:"goat",ko:"염소"},{w:"rabbit",ko:"토끼"},{w:"mouse",ko:"쥐"},{w:"tiger",ko:"호랑이"},
{w:"lion",ko:"사자"},{w:"bear",ko:"곰"},{w:"elephant",ko:"코끼리"},{w:"monkey",ko:"원숭이"},
{w:"snake",ko:"뱀"},{w:"frog",ko:"개구리"},{w:"insect",ko:"곤충"},{w:"bee",ko:"벌"},
{w:"butterfly",ko:"나비"},{w:"spider",ko:"거미"},{w:"ant",ko:"개미"},{w:"duck",ko:"오리"},
{w:"chick",ko:"병아리"},{w:"whale",ko:"고래"},{w:"shark",ko:"상어"},{w:"dolphin",ko:"돌고래"},
{w:"turtle",ko:"거북이"},{w:"deer",ko:"사슴"},{w:"fox",ko:"여우"},{w:"wolf",ko:"늑대"},
{w:"tail",ko:"꼬리"},{w:"wing",ko:"날개"},{w:"feather",ko:"깃털"},{w:"pet",ko:"반려동물"},
// 장소·도시·교통
{w:"place",ko:"장소"},{w:"city",ko:"도시"},{w:"town",ko:"마을"},{w:"village",ko:"시골 마을"},
{w:"country",ko:"나라, 시골"},{w:"street",ko:"거리"},{w:"road",ko:"도로"},{w:"bridge",ko:"다리"},
{w:"building",ko:"건물"},{w:"school",ko:"학교"},{w:"library",ko:"도서관"},{w:"museum",ko:"박물관"},
{w:"park",ko:"공원"},{w:"market",ko:"시장"},{w:"store",ko:"상점"},{w:"shop",ko:"가게"},
{w:"mall",ko:"쇼핑몰"},{w:"restaurant",ko:"식당"},{w:"cafe",ko:"카페"},{w:"bank",ko:"은행"},
{w:"church",ko:"교회"},{w:"station",ko:"역"},{w:"airport",ko:"공항"},{w:"factory",ko:"공장"},
{w:"office",ko:"사무실"},{w:"farm",ko:"농장"},{w:"zoo",ko:"동물원"},{w:"theater",ko:"극장"},
{w:"hotel",ko:"호텔"},{w:"pharmacy",ko:"약국"},{w:"car",ko:"자동차"},{w:"bus",ko:"버스"},
{w:"taxi",ko:"택시"},{w:"train",ko:"기차"},{w:"subway",ko:"지하철"},{w:"airplane",ko:"비행기"},
{w:"ship",ko:"배"},{w:"boat",ko:"보트"},{w:"bicycle",ko:"자전거"},{w:"motorcycle",ko:"오토바이"},
{w:"truck",ko:"트럭"},{w:"ticket",ko:"표"},{w:"map",ko:"지도"},{w:"traffic",ko:"교통"},
{w:"corner",ko:"모퉁이"},{w:"sidewalk",ko:"인도"},{w:"crosswalk",ko:"횡단보도"},{w:"signal",ko:"신호"},
// 기본 동사 (동작)
{w:"go",ko:"가다"},{w:"come",ko:"오다"},{w:"walk",ko:"걷다"},{w:"run",ko:"달리다"},
{w:"jump",ko:"뛰어오르다"},{w:"sit",ko:"앉다"},{w:"stand",ko:"서다"},{w:"lie",ko:"눕다, 거짓말하다"},
{w:"sleep",ko:"자다"},{w:"wake",ko:"깨다"},{w:"open",ko:"열다"},{w:"close",ko:"닫다"},
{w:"push",ko:"밀다"},{w:"pull",ko:"당기다"},{w:"throw",ko:"던지다"},{w:"catch",ko:"잡다"},
{w:"hold",ko:"잡다, 들다"},{w:"carry",ko:"나르다"},{w:"bring",ko:"가져오다"},{w:"take",ko:"가져가다, 취하다"},
{w:"give",ko:"주다"},{w:"send",ko:"보내다"},{w:"receive",ko:"받다"},{w:"buy",ko:"사다"},
{w:"sell",ko:"팔다"},{w:"pay",ko:"지불하다"},{w:"borrow",ko:"빌리다"},{w:"lend",ko:"빌려주다"},
{w:"keep",ko:"유지하다, 간직하다"},{w:"lose",ko:"잃다, 지다"},{w:"find",ko:"찾다"},{w:"search",ko:"찾다, 검색하다"},
{w:"use",ko:"사용하다"},{w:"make",ko:"만들다"},{w:"build",ko:"짓다"},{w:"break",ko:"깨다, 부수다"},
{w:"fix",ko:"고치다"},{w:"clean",ko:"청소하다"},{w:"wash",ko:"씻다"},{w:"wipe",ko:"닦다"},
{w:"throw away",ko:"버리다"},{w:"move",ko:"움직이다, 이사하다"},{w:"turn",ko:"돌다, 켜다/끄다"},{w:"stop",ko:"멈추다"},
{w:"start",ko:"시작하다"},{w:"begin",ko:"시작하다"},{w:"finish",ko:"끝내다"},{w:"continue",ko:"계속하다"},
{w:"wait",ko:"기다리다"},{w:"hurry",ko:"서두르다"},{w:"follow",ko:"따라가다"},{w:"lead",ko:"이끌다"},
{w:"meet",ko:"만나다"},{w:"visit",ko:"방문하다"},{w:"join",ko:"참여하다"},{w:"leave",ko:"떠나다, 남기다"},
{w:"stay",ko:"머무르다"},{w:"return",ko:"돌아오다"},{w:"arrive",ko:"도착하다"},{w:"enter",ko:"들어가다"},
{w:"exit",ko:"나가다"},{w:"climb",ko:"오르다"},{w:"fall",ko:"떨어지다, 넘어지다"},{w:"fly",ko:"날다"},
{w:"swim",ko:"수영하다"},{w:"dance",ko:"춤추다"},{w:"sing",ko:"노래하다"},{w:"play",ko:"놀다, 연주하다"},
{w:"draw",ko:"그리다"},{w:"paint",ko:"색칠하다, 그리다"},{w:"write",ko:"쓰다"},{w:"read",ko:"읽다"},
{w:"speak",ko:"말하다"},{w:"talk",ko:"이야기하다"},{w:"say",ko:"말하다"},{w:"tell",ko:"말하다, 알리다"},
{w:"ask",ko:"묻다, 요청하다"},{w:"answer",ko:"대답하다"},{w:"call",ko:"부르다, 전화하다"},{w:"shout",ko:"외치다"},
{w:"whisper",ko:"속삭이다"},{w:"listen",ko:"듣다"},{w:"hear",ko:"들리다"},{w:"look",ko:"보다"},
{w:"see",ko:"보다, 알다"},{w:"watch",ko:"지켜보다"},{w:"show",ko:"보여주다"},{w:"hide",ko:"숨기다"},
{w:"smile",ko:"미소 짓다"},{w:"laugh",ko:"웃다"},{w:"cry",ko:"울다"},{w:"touch",ko:"만지다"},
{w:"feel",ko:"느끼다"},{w:"smell",ko:"냄새 맡다"},{w:"kiss",ko:"입맞추다"},{w:"hug",ko:"껴안다"},
// 생각·소통 동사
{w:"think",ko:"생각하다"},{w:"know",ko:"알다"},{w:"understand",ko:"이해하다"},{w:"remember",ko:"기억하다"},
{w:"forget",ko:"잊다"},{w:"learn",ko:"배우다"},{w:"teach",ko:"가르치다"},{w:"study",ko:"공부하다"},
{w:"believe",ko:"믿다"},{w:"hope",ko:"희망하다"},{w:"wish",ko:"바라다"},{w:"want",ko:"원하다"},
{w:"need",ko:"필요하다"},{w:"like",ko:"좋아하다"},{w:"love",ko:"사랑하다"},{w:"hate",ko:"싫어하다"},
{w:"prefer",ko:"더 좋아하다"},{w:"choose",ko:"고르다"},{w:"decide",ko:"결정하다"},{w:"agree",ko:"동의하다"},
{w:"disagree",ko:"반대하다"},{w:"promise",ko:"약속하다"},{w:"explain",ko:"설명하다"},{w:"describe",ko:"묘사하다"},
{w:"suggest",ko:"제안하다"},{w:"invite",ko:"초대하다"},{w:"thank",ko:"감사하다"},{w:"apologize",ko:"사과하다"},
{w:"complain",ko:"불평하다"},{w:"worry",ko:"걱정하다"},{w:"enjoy",ko:"즐기다"},{w:"prepare",ko:"준비하다"},
{w:"plan",ko:"계획하다"},{w:"try",ko:"시도하다"},{w:"practice",ko:"연습하다"},{w:"repeat",ko:"반복하다"},
{w:"check",ko:"확인하다"},{w:"compare",ko:"비교하다"},{w:"change",ko:"바꾸다"},{w:"help",ko:"돕다"},
{w:"save",ko:"구하다, 저축하다"},{w:"spend",ko:"쓰다, 보내다"},{w:"share",ko:"나누다, 공유하다"},{w:"count",ko:"세다"},
// 감정·상태
{w:"happy",ko:"행복한"},{w:"glad",ko:"기쁜"},{w:"sad",ko:"슬픈"},{w:"angry",ko:"화난"},
{w:"afraid",ko:"두려운"},{w:"scared",ko:"겁먹은"},{w:"surprised",ko:"놀란"},{w:"excited",ko:"신난"},
{w:"bored",ko:"지루한"},{w:"nervous",ko:"긴장한"},{w:"worried",ko:"걱정하는"},{w:"lonely",ko:"외로운"},
{w:"proud",ko:"자랑스러운"},{w:"shy",ko:"수줍은"},{w:"calm",ko:"차분한"},{w:"upset",ko:"속상한"},
{w:"comfortable",ko:"편안한"},{w:"confident",ko:"자신 있는"},{w:"jealous",ko:"질투하는"},{w:"curious",ko:"호기심 있는"},
{w:"feeling",ko:"감정, 느낌"},{w:"mood",ko:"기분"},{w:"smart",ko:"똑똑한"},{w:"clever",ko:"영리한"},
{w:"kind",ko:"친절한"},{w:"nice",ko:"좋은, 멋진"},{w:"friendly",ko:"다정한"},{w:"polite",ko:"예의 바른"},
{w:"rude",ko:"무례한"},{w:"honest",ko:"정직한"},{w:"lazy",ko:"게으른"},{w:"diligent",ko:"부지런한"},
{w:"brave",ko:"용감한"},{w:"careful",ko:"조심스러운"},{w:"careless",ko:"부주의한"},{w:"funny",ko:"웃긴"},
{w:"serious",ko:"진지한"},{w:"quiet",ko:"조용한"},{w:"cheerful",ko:"쾌활한"},{w:"generous",ko:"너그러운"},
// 학교·공부
{w:"teacher",ko:"선생님"},{w:"student",ko:"학생"},{w:"class",ko:"수업, 반"},{w:"classroom",ko:"교실"},
{w:"lesson",ko:"수업, 과"},{w:"homework",ko:"숙제"},{w:"exam",ko:"시험"},{w:"test",ko:"시험"},
{w:"grade",ko:"성적, 학년"},{w:"subject",ko:"과목"},{w:"math",ko:"수학"},{w:"science",ko:"과학"},
{w:"history",ko:"역사"},{w:"English",ko:"영어"},{w:"language",ko:"언어"},{w:"book",ko:"책"},
{w:"notebook",ko:"공책"},{w:"pencil",ko:"연필"},{w:"pen",ko:"펜"},{w:"eraser",ko:"지우개"},
{w:"ruler",ko:"자"},{w:"paper",ko:"종이"},{w:"page",ko:"쪽"},{w:"word",ko:"단어"},
{w:"sentence",ko:"문장"},{w:"question",ko:"질문"},{w:"problem",ko:"문제"},{w:"example",ko:"예시"},
{w:"answer",ko:"답"},{w:"mistake",ko:"실수"},{w:"score",ko:"점수"},{w:"college",ko:"대학"},
{w:"university",ko:"대학교"},{w:"degree",ko:"학위"},{w:"knowledge",ko:"지식"},{w:"idea",ko:"생각"},
// 색·모양·숫자
{w:"color",ko:"색"},{w:"red",ko:"빨강"},{w:"blue",ko:"파랑"},{w:"yellow",ko:"노랑"},
{w:"green",ko:"초록"},{w:"black",ko:"검정"},{w:"white",ko:"하양"},{w:"gray",ko:"회색"},
{w:"brown",ko:"갈색"},{w:"pink",ko:"분홍"},{w:"purple",ko:"보라"},{w:"gold",ko:"금색"},
{w:"shape",ko:"모양"},{w:"circle",ko:"원"},{w:"square",ko:"사각형"},{w:"triangle",ko:"삼각형"},
{w:"line",ko:"선"},{w:"point",ko:"점"},{w:"number",ko:"숫자"},{w:"zero",ko:"영"},
{w:"hundred",ko:"백"},{w:"thousand",ko:"천"},{w:"million",ko:"백만"},{w:"half",ko:"절반"},
{w:"double",ko:"두 배"},{w:"single",ko:"하나의"},{w:"pair",ko:"한 쌍"},{w:"dozen",ko:"열두 개"},
{w:"first",ko:"첫 번째"},{w:"second",ko:"두 번째"},{w:"last",ko:"마지막"},{w:"next",ko:"다음"},
// 직업·일
{w:"job",ko:"일, 직업"},{w:"work",ko:"일하다, 일"},{w:"worker",ko:"노동자"},{w:"boss",ko:"상사"},
{w:"engineer",ko:"기술자"},{w:"police",ko:"경찰"},{w:"firefighter",ko:"소방관"},{w:"farmer",ko:"농부"},
{w:"cook",ko:"요리사"},{w:"waiter",ko:"종업원"},{w:"driver",ko:"운전사"},{w:"pilot",ko:"조종사"},
{w:"artist",ko:"예술가"},{w:"singer",ko:"가수"},{w:"actor",ko:"배우"},{w:"writer",ko:"작가"},
{w:"lawyer",ko:"변호사"},{w:"scientist",ko:"과학자"},{w:"soldier",ko:"군인"},{w:"clerk",ko:"점원"},
{w:"manager",ko:"관리자"},{w:"customer",ko:"고객"},{w:"company",ko:"회사"},{w:"salary",ko:"급여"},
{w:"career",ko:"경력"},{w:"meeting",ko:"회의"},{w:"project",ko:"프로젝트"},{w:"team",ko:"팀"},
{w:"busy",ko:"바쁜"},{w:"free",ko:"한가한, 무료의"},{w:"retire",ko:"은퇴하다"},{w:"hire",ko:"고용하다"},
// 돈·쇼핑
{w:"money",ko:"돈"},{w:"cash",ko:"현금"},{w:"coin",ko:"동전"},{w:"price",ko:"가격"},
{w:"cost",ko:"비용, 비용이 들다"},{w:"expensive",ko:"비싼"},{w:"cheap",ko:"싼"},{w:"free",ko:"무료의"},
{w:"discount",ko:"할인"},{w:"sale",ko:"판매, 할인"},{w:"receipt",ko:"영수증"},{w:"change",ko:"거스름돈"},
{w:"card",ko:"카드"},{w:"account",ko:"계좌"},{w:"save",ko:"저축하다"},{w:"rich",ko:"부유한"},
{w:"poor",ko:"가난한"},{w:"cheaper",ko:"더 싼"},{w:"order",ko:"주문하다"},{w:"deliver",ko:"배달하다"},
{w:"customer",ko:"손님"},{w:"refund",ko:"환불"},{w:"bargain",ko:"흥정하다"},{w:"afford",ko:"형편이 되다"},
// 여행·통신·기술
{w:"travel",ko:"여행하다"},{w:"trip",ko:"여행"},{w:"journey",ko:"여정"},{w:"tour",ko:"관광"},
{w:"passport",ko:"여권"},{w:"luggage",ko:"짐"},{w:"suitcase",ko:"여행 가방"},{w:"camera",ko:"카메라"},
{w:"photo",ko:"사진"},{w:"souvenir",ko:"기념품"},{w:"abroad",ko:"해외에"},{w:"foreign",ko:"외국의"},
{w:"reservation",ko:"예약"},{w:"flight",ko:"항공편"},{w:"gate",ko:"탑승구"},{w:"phone",ko:"전화"},
{w:"message",ko:"메시지"},{w:"email",ko:"이메일"},{w:"internet",ko:"인터넷"},{w:"computer",ko:"컴퓨터"},
{w:"screen",ko:"화면"},{w:"keyboard",ko:"키보드"},{w:"password",ko:"비밀번호"},{w:"website",ko:"웹사이트"},
{w:"app",ko:"앱"},{w:"news",ko:"뉴스"},{w:"radio",ko:"라디오"},{w:"television",ko:"텔레비전"},
{w:"movie",ko:"영화"},{w:"music",ko:"음악"},{w:"song",ko:"노래"},{w:"game",ko:"게임"},
{w:"hobby",ko:"취미"},{w:"sport",ko:"운동"},{w:"exercise",ko:"운동(하다)"},{w:"team",ko:"팀"},
// 위치·방향·수량
{w:"up",ko:"위로"},{w:"down",ko:"아래로"},{w:"left",ko:"왼쪽"},{w:"right",ko:"오른쪽"},
{w:"front",ko:"앞"},{w:"side",ko:"옆, 측면"},{w:"top",ko:"꼭대기"},{w:"bottom",ko:"바닥"},
{w:"middle",ko:"가운데"},{w:"inside",ko:"안쪽"},{w:"outside",ko:"바깥쪽"},{w:"near",ko:"가까운"},
{w:"far",ko:"먼"},{w:"north",ko:"북쪽"},{w:"south",ko:"남쪽"},{w:"east",ko:"동쪽"},
{w:"west",ko:"서쪽"},{w:"direction",ko:"방향"},{w:"distance",ko:"거리"},{w:"between",ko:"~사이에"},
{w:"around",ko:"주위에"},{w:"many",ko:"많은(셀 수 있는)"},{w:"much",ko:"많은(셀 수 없는)"},{w:"few",ko:"거의 없는"},
{w:"little",ko:"적은, 작은"},{w:"some",ko:"약간의"},{w:"all",ko:"모든"},{w:"every",ko:"모든"},
{w:"each",ko:"각각의"},{w:"more",ko:"더 많은"},{w:"less",ko:"더 적은"},{w:"most",ko:"대부분"},
{w:"enough",ko:"충분한"},{w:"empty",ko:"빈"},{w:"full",ko:"가득 찬"},{w:"whole",ko:"전체의"},
// 자주 쓰는 형용사·부사
{w:"good",ko:"좋은"},{w:"bad",ko:"나쁜"},{w:"big",ko:"큰"},{w:"small",ko:"작은"},
{w:"long",ko:"긴"},{w:"high",ko:"높은"},{w:"low",ko:"낮은"},{w:"wide",ko:"넓은"},
{w:"narrow",ko:"좁은"},{w:"deep",ko:"깊은"},{w:"heavy",ko:"무거운"},{w:"light",ko:"가벼운, 밝은"},
{w:"fast",ko:"빠른"},{w:"slow",ko:"느린"},{w:"easy",ko:"쉬운"},{w:"difficult",ko:"어려운"},
{w:"hard",ko:"어려운, 단단한"},{w:"soft",ko:"부드러운"},{w:"new",ko:"새로운"},{w:"clean",ko:"깨끗한"},
{w:"dirty",ko:"더러운"},{w:"important",ko:"중요한"},{w:"useful",ko:"유용한"},{w:"simple",ko:"간단한"},
{w:"famous",ko:"유명한"},{w:"true",ko:"사실인"},{w:"false",ko:"거짓의"},{w:"real",ko:"진짜의"},
{w:"same",ko:"같은"},{w:"different",ko:"다른"},{w:"special",ko:"특별한"},{w:"normal",ko:"보통의"},
{w:"strange",ko:"이상한"},{w:"dangerous",ko:"위험한"},{w:"safe",ko:"안전한"},{w:"possible",ko:"가능한"},
{w:"sure",ko:"확실한"},{w:"ready",ko:"준비된"},{w:"alone",ko:"혼자인"},{w:"together",ko:"함께"},
{w:"again",ko:"다시"},{w:"really",ko:"정말로"},{w:"very",ko:"매우"},{w:"too",ko:"너무, ~도"},
{w:"almost",ko:"거의"},{w:"maybe",ko:"아마"},{w:"perhaps",ko:"아마도"},{w:"quickly",ko:"빠르게"},
{w:"slowly",ko:"천천히"},{w:"carefully",ko:"조심스럽게"},{w:"suddenly",ko:"갑자기"},{w:"finally",ko:"마침내"},
// 일상 행동·기타 명사
{w:"life",ko:"삶"},{w:"world",ko:"세계"},{w:"thing",ko:"것, 물건"},{w:"way",ko:"방법, 길"},
{w:"part",ko:"부분"},{w:"reason",ko:"이유"},{w:"result",ko:"결과"},{w:"chance",ko:"기회"},
{w:"matter",ko:"문제, 중요하다"},{w:"news",ko:"소식"},{w:"story",ko:"이야기"},{w:"fact",ko:"사실"},
{w:"event",ko:"행사, 사건"},{w:"party",ko:"파티"},{w:"gift",ko:"선물"},{w:"present",ko:"선물, 현재의"},
{w:"sound",ko:"소리"},{w:"voice",ko:"목소리"},{w:"noise",ko:"소음"},{w:"smell",ko:"냄새"},
{w:"light",ko:"빛"},{w:"shadow",ko:"그림자"},{w:"shape",ko:"형태"},{w:"piece",ko:"조각"},
{w:"box",ko:"상자"},{w:"bag",ko:"봉지"},{w:"basket",ko:"바구니"},{w:"umbrella",ko:"우산"},
{w:"newspaper",ko:"신문"},{w:"letter",ko:"편지, 글자"},{w:"picture",ko:"그림, 사진"},{w:"toy",ko:"장난감"},
{w:"ball",ko:"공"},{w:"flag",ko:"깃발"},{w:"candle",ko:"양초"},{w:"battery",ko:"건전지"},
{w:"machine",ko:"기계"},{w:"tool",ko:"도구"},{w:"wheel",ko:"바퀴"},{w:"engine",ko:"엔진"},
{w:"garden",ko:"정원"},{w:"yard",ko:"마당"},{w:"gate",ko:"대문"},{w:"fence",ko:"울타리"},
{w:"address",ko:"주소"},{w:"area",ko:"지역"},{w:"space",ko:"공간, 우주"},{w:"center",ko:"중심"},
{w:"weight",ko:"무게"},{w:"height",ko:"높이, 키"},{w:"length",ko:"길이"},{w:"speed",ko:"속도"},
{w:"sleep",ko:"잠"},{w:"dream",ko:"꿈"},{w:"rest",ko:"휴식"},{w:"fun",ko:"재미"},
{w:"luck",ko:"운"},{w:"power",ko:"힘, 전력"},{w:"energy",ko:"에너지"},{w:"peace",ko:"평화"},
{w:"war",ko:"전쟁"},{w:"law",ko:"법"},{w:"rule",ko:"규칙"},{w:"right",ko:"권리"},
{w:"truth",ko:"진실"},{w:"hope",ko:"희망"},{w:"future",ko:"미래"},{w:"past",ko:"과거"},
// 추가 일상 단어
{w:"morning routine",ko:"아침 일과"},{w:"breakfast time",ko:"아침 식사 시간"},{w:"brush",ko:"빗다, 솔질하다"},{w:"comb",ko:"빗"},
{w:"shampoo",ko:"샴푸"},{w:"shower",ko:"샤워"},{w:"bath",ko:"목욕"},{w:"makeup",ko:"화장"},
{w:"shave",ko:"면도하다"},{w:"sweat",ko:"땀"},{w:"breath",ko:"숨"},{w:"yawn",ko:"하품하다"},
{w:"sneeze",ko:"재채기하다"},{w:"blink",ko:"눈을 깜빡이다"},{w:"nod",ko:"고개를 끄덕이다"},{w:"wave",ko:"손을 흔들다"},
{w:"point",ko:"가리키다"},{w:"kick",ko:"차다"},{w:"hit",ko:"치다"},{w:"bite",ko:"물다"},
{w:"lick",ko:"핥다"},{w:"grab",ko:"움켜잡다"},{w:"drop",ko:"떨어뜨리다"},{w:"pick",ko:"고르다, 줍다"},
{w:"shake",ko:"흔들다"},{w:"press",ko:"누르다"},{w:"squeeze",ko:"짜다"},{w:"tear",ko:"찢다, 눈물"},
{w:"fold",ko:"접다"},{w:"tie",ko:"묶다"},{w:"hang",ko:"걸다"},{w:"pour",ko:"붓다"},
{w:"fill",ko:"채우다"},{w:"spill",ko:"엎지르다"},{w:"melt",ko:"녹다"},{w:"freeze",ko:"얼다"},
{w:"burn",ko:"타다, 데다"},{w:"shine",ko:"빛나다"},{w:"glow",ko:"은은히 빛나다"},{w:"flow",ko:"흐르다"},
{w:"float",ko:"뜨다"},{w:"sink",ko:"가라앉다"},{w:"roll",ko:"구르다"},{w:"spin",ko:"돌다"},
{w:"bend",ko:"구부리다"},{w:"stretch",ko:"늘이다, 뻗다"},{w:"crawl",ko:"기어가다"},{w:"slide",ko:"미끄러지다"},
{w:"chase",ko:"쫓다"},{w:"escape",ko:"달아나다"},{w:"hunt",ko:"사냥하다"},{w:"feed",ko:"먹이다"},
{w:"grow",ko:"자라다, 기르다"},{w:"raise",ko:"기르다, 올리다"},{w:"protect",ko:"보호하다"},{w:"care",ko:"돌보다, 신경 쓰다"},
{w:"trust",ko:"신뢰하다"},{w:"respect",ko:"존경하다"},{w:"forgive",ko:"용서하다"},{w:"blame",ko:"탓하다"},
{w:"argue",ko:"말다툼하다"},{w:"fight",ko:"싸우다"},{w:"win",ko:"이기다"},{w:"lose",ko:"지다"},
{w:"beat",ko:"이기다, 두드리다"},{w:"compete",ko:"경쟁하다"},{w:"succeed",ko:"성공하다"},{w:"fail",ko:"실패하다"},
{w:"happen",ko:"일어나다"},{w:"appear",ko:"나타나다"},{w:"disappear",ko:"사라지다"},{w:"seem",ko:"~인 것 같다"},
{w:"become",ko:"~이 되다"},{w:"belong",ko:"속하다"},{w:"contain",ko:"담고 있다"},{w:"include",ko:"포함하다"},
{w:"depend",ko:"의존하다"},{w:"affect",ko:"영향을 주다"},{w:"cause",ko:"~을 야기하다"},{w:"create",ko:"창조하다"},
{w:"destroy",ko:"파괴하다"},{w:"discover",ko:"발견하다"},{w:"invent",ko:"발명하다"},{w:"imagine",ko:"상상하다"},
{w:"realize",ko:"깨닫다"},{w:"recognize",ko:"알아보다"},{w:"notice",ko:"알아차리다"},{w:"expect",ko:"기대하다"},
{w:"guess",ko:"추측하다"},{w:"doubt",ko:"의심하다"},{w:"mean",ko:"의미하다"},{w:"matter",ko:"중요하다"},
{w:"allow",ko:"허락하다"},{w:"refuse",ko:"거절하다"},{w:"accept",ko:"받아들이다"},{w:"offer",ko:"제안하다"},
{w:"provide",ko:"제공하다"},{w:"supply",ko:"공급하다"},{w:"deliver",ko:"배달하다"},{w:"deal",ko:"다루다, 거래"},
{w:"manage",ko:"관리하다, 해내다"},{w:"control",ko:"통제하다"},{w:"organize",ko:"정리하다"},{w:"arrange",ko:"마련하다"}
];
